In [1]:
from quchem.Hamiltonian_Generator_Functions import *
from quchem.Graph import *
### HAMILTONIAN start
Molecule = 'LiH'
geometry = None # [('H', (0., 0., 0.)), ('H', (0., 0., 0.74))]
basis = 'sto-6g'


### Get Hamiltonian
Hamilt = Hamiltonian_PySCF(Molecule,
                     run_scf=1, run_mp2=1, run_cisd=1, run_ccsd=1, run_fci=1,
                     basis=basis,
                     multiplicity=1,
                     geometry=geometry)  # normally None!
QubitHamiltonian = Hamilt.Get_Qubit_Hamiltonian(threshold=None, transformation='BK')
### HAMILTONIAN end
QubitHamiltonian

(-3.9899724181893785+0j) [] +
(0.040374603256426736+0j) [X0 X1 X2] +
(-0.0031615876042060858+0j) [X0 X1 X2 X3 Y7 Y11] +
(0.0016204769263748853+0j) [X0 X1 X2 Y3 Y5] +
(0.003650850255676717+0j) [X0 X1 X2 Z3] +
(0.0018998726581464286+0j) [X0 X1 Z2 X3 Y7 Z9 Y10 X11] +
(0.004695260540246557+0j) [X0 X1 Z2 Y3 Y4 X5] +
(-0.001211302713482722+0j) [X0 X1 X3 X4 Y7 Y11] +
(0.0010441957704835074+0j) [X0 X1 X3 Y4 Y5 Z6 Z7] +
(0.001211302713482722+0j) [X0 X1 X3 Y4 Z5 Y7 Z9 Z10 X11] +
(0.0025594391105539667+0j) [X0 X1 X3 Z4 Y5 Y6 Z7] +
(6.6485812068864e-05+0j) [X0 X1 X3 Z4 Z5 Y7 Z9 Y10 X11] +
(0.001277788525551586+0j) [X0 X1 X3 Z4 Y7 Z9 Y10 X11] +
(0.0009618499558327561+0j) [X0 X1 X3 X6 Y7 Y11] +
(-0.00015670172210397243+0j) [X0 X1 X3 Z6 Y7 Z9 Y10 X11] +
(0.0009618499558327561+0j) [X0 X1 X3 Y7 X8 Y11] +
(-0.0009618499558327561+0j) [X0 X1 X3 Y7 Y8 Z10 X11] +
(-0.00015670172210397503+0j) [X0 X1 X3 Y7 Z8 Z9 Y10 X11] +
(0.0008051482337287812+0j) [X0 X1 X3 Y7 Z8 Y10 X11] +
(0.015294910119292137+0j) [X0 X1 

In [2]:
from quchem.Ansatz_Generator_Functions import *


ansatz_obj = Ansatz(Hamilt.molecule.n_electrons, Hamilt.molecule.n_qubits)

print('JW ground state = ', ansatz_obj.Get_JW_HF_state_in_OCC_basis())
print('BK ground state = ', ansatz_obj.Get_BK_HF_state_in_OCC_basis())

JW ground state =  [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
BK ground state =  [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


The LiH ground state under JW is:

$$|\psi \rangle_{HF}^{ground} = | 1 1 1 1 \:  0 0 0 0 0 0 0 0 \rangle$$

and under BK is:

$$|\psi \rangle_{HF}^{ground} = | 1 0 1 0 0 0 0 0 0 0 0 0 \rangle$$

### Look at NATURAL orbital occupations!

In [3]:
NOON_spins_combined, NMO_basis = Hamilt.Get_NOON()
##
Hamilt.Get_CCSD_Amplitudes()

NOON_spins_combined

print(print(np.around(np.diag(NOON_spins_combined), 5)))

[[1.99992e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 1.96765e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 2.71800e-02 0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 2.59000e-03 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 2.59000e-03 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 8.00000e-05]]
None


This shows that orbitals (0,1) are nearly always FILLED
and
orbitals (10,11) are nearly always UNILLED!

In paper: PHYS. REV. X, **8**, 031022 (2018)
- active space chosen to be **spatial orbitals** 1-4 (aka spin orbital indices (2,3),(4,5),(6,7),(8,9)
- aka to simply problem here orbitals (8,9) also assumed to be empty!


In [4]:
from quchem.Ansatz_Generator_Functions import *


ansatz_obj = Ansatz(Hamilt.molecule.n_electrons, Hamilt.molecule.n_qubits)



Sec_Quant_CC_ops_ia, Sec_Quant_CC_ops_ijab, theta_parameters_ia, theta_parameters_ijab=ansatz_obj.Get_ia_and_ijab_terms(single_cc_amplitudes=None, 
                                                                                                             double_cc_amplitudes=None, 
                                                                                                             singles_hamiltonian=None,
                                                                                                             doubles_hamiltonian=None, 
                                                                                                             tol_filter_small_terms = None)

Sec_Quant_CC_ops_ia

[-1.0 [0^ 4] +
 1.0 [4^ 0],
 -1.0 [0^ 6] +
 1.0 [6^ 0],
 -1.0 [0^ 8] +
 1.0 [8^ 0],
 -1.0 [0^ 10] +
 1.0 [10^ 0],
 -1.0 [2^ 4] +
 1.0 [4^ 2],
 -1.0 [2^ 6] +
 1.0 [6^ 2],
 -1.0 [2^ 8] +
 1.0 [8^ 2],
 -1.0 [2^ 10] +
 1.0 [10^ 2],
 -1.0 [1^ 5] +
 1.0 [5^ 1],
 -1.0 [1^ 7] +
 1.0 [7^ 1],
 -1.0 [1^ 9] +
 1.0 [9^ 1],
 -1.0 [1^ 11] +
 1.0 [11^ 1],
 -1.0 [3^ 5] +
 1.0 [5^ 3],
 -1.0 [3^ 7] +
 1.0 [7^ 3],
 -1.0 [3^ 9] +
 1.0 [9^ 3],
 -1.0 [3^ 11] +
 1.0 [11^ 3]]

# Remove fermionic terms we are NOT taking into account

In [5]:
ansatz_obj = BK_Qubit_Reduction(QubitHamiltonian,
                             Hamilt.molecule.n_electrons,
                             Hamilt.molecule.n_qubits)

In [6]:
indices_to_KEEP = [2,3,4,5,6,7]

NEW_Sec_Quant_CC_ops_ia, NEW_Sec_Quant_CC_ops_ijab, theta_ia, theta_ijab = ansatz_obj.Reduced_ia_ijab_terms(
                                         Hamilt.molecule.n_qubits, 
                                         Hamilt.molecule.n_electrons, 
                                         indices_to_KEEP)
NEW_Sec_Quant_CC_ops_ia

[-1.0 [2^ 4] +
 1.0 [4^ 2],
 -1.0 [2^ 6] +
 1.0 [6^ 2],
 -1.0 [3^ 5] +
 1.0 [5^ 3],
 -1.0 [3^ 7] +
 1.0 [7^ 3]]

In [7]:
NEW_Sec_Quant_CC_ops_ijab

[-1.0 [2^ 3^ 4 5] +
 1.0 [5^ 4^ 3 2],
 -1.0 [2^ 3^ 4 7] +
 1.0 [7^ 4^ 3 2],
 -1.0 [2^ 3^ 6 7] +
 1.0 [7^ 6^ 3 2]]

In [8]:
# REDUCTION
Qubit_Op_list_Second_Quant_CC_Ops_ia, Qubit_Op_list_Second_Quant_CC_Ops_ijab = ansatz_obj.UCCSD_single_trotter_step(
                        NEW_Sec_Quant_CC_ops_ia,
                        NEW_Sec_Quant_CC_ops_ijab,
                        transformation='BK')
# Qubit_Op_list_Second_Quant_CC_Ops_ijab

In [9]:
print('finding DOUBLE e- operators only acted on by I or Z')
print('')
print(Qubit_Op_list_Second_Quant_CC_Ops_ijab)

indices_to_Remove_ijab = ansatz_obj.Find_Qubits_only_acted_on_by_I_or_Z(Qubit_Op_list_Second_Quant_CC_Ops_ijab)
print('')
print('qubit indices:', indices_to_Remove_ijab, 'only acted on by I or Z')

finding DOUBLE e- operators only acted on by I or Z

[0.125j [Z1 X2 Z3 Y4] +
0.125j [Z1 X2 Z3 Y4 Z5] +
-0.125j [Z1 Y2 Z3 X4] +
-0.125j [Z1 Y2 Z3 X4 Z5] +
0.125j [X2 Y4] +
0.125j [X2 Y4 Z5] +
-0.125j [Y2 X4] +
-0.125j [Y2 X4 Z5], 0.125j [Z1 X2 Z3 X4 Y5 Z6] +
0.125j [Z1 X2 Y4 X5 Z7] +
0.125j [Z1 Y2 Z3 Y4 Y5 Z6] +
-0.125j [Z1 Y2 X4 X5 Z7] +
0.125j [X2 Z3 Y4 X5 Z7] +
0.125j [X2 X4 Y5 Z6] +
-0.125j [Y2 Z3 X4 X5 Z7] +
0.125j [Y2 Y4 Y5 Z6], 0.125j [Z1 X2 Z3 Y6] +
0.125j [Z1 X2 Z5 Y6 Z7] +
-0.125j [Z1 Y2 Z3 X6] +
-0.125j [Z1 Y2 Z5 X6 Z7] +
0.125j [X2 Z3 Z5 Y6 Z7] +
0.125j [X2 Y6] +
-0.125j [Y2 Z3 Z5 X6 Z7] +
-0.125j [Y2 X6]]

qubit indices: [ 0  1  3  7  8  9 10 11] only acted on by I or Z


In [10]:
print('finding SINGLE e- operators only acted on by I or Z')
print('')
print(Qubit_Op_list_Second_Quant_CC_Ops_ia)

indices_to_Remove_ia = ansatz_obj.Find_Qubits_only_acted_on_by_I_or_Z(Qubit_Op_list_Second_Quant_CC_Ops_ia)
print('')
print('qubit indices:', indices_to_Remove_ia, 'only acted on by I or Z')

finding SINGLE e- operators only acted on by I or Z

[0.5j [Z1 X2 Y3 X4] +
0.5j [Z1 Y2 Y3 Y4], 0.5j [Z1 X2 Y3 Z5 X6] +
0.5j [Z1 Y2 Y3 Z5 Y6], 0.5j [Z1 Z2 Y3 Z4 X5] +
-0.5j [X3 Y5], 0.5j [Z1 Z2 Y3 Z5 Z6] +
-0.5j [Y3 Z7]]

qubit indices: [ 0  1  7  8  9 10 11] only acted on by I or Z


#### find overlap of allowed indices to remove

In [11]:
indices_to_Remove = list(set(indices_to_Remove_ijab).intersection(indices_to_Remove_ia))
indices_to_Remove

[0, 1, 7, 8, 9, 10, 11]

In [12]:
# only Z terms in H remain!!!!!
from openfermion import qubit_operator_sparse
from openfermion.ops import QubitOperator

MAT = qubit_operator_sparse(QubitOperator('Z0 X1', 1))

zero = np.array([[1],[0]])
one = np.array([[0],[1]])

state = reduce(np.kron, [one, zero])

state.conj().transpose().dot(MAT.todense().dot(state))

matrix([[0.+0.j]])

### Can remove these terms from Hamiltonian

In [13]:
reduced_Qubit_Hamiltonian = ansatz_obj.Remove_indices_from_Hamiltonian(indices_to_Remove)
reduced_Qubit_Hamiltonian

(-7.27686951249773+0j) [] +
(0.00934468360804178+0j) [X2 X3 X4 X5] +
(-0.000276346968974246+0j) [X2 X3 Y4 Y5 Z6] +
(0.004836443728006368+0j) [X2 X3 Z4 Y5 Y6] +
(0.00032184554262421473+0j) [X2 Y3 X4 Y5] +
(0.00473907074718689+0j) [X2 Y3 Y4 X5] +
(0.004560096759032121+0j) [X2 Y3 Y4 X5 Z6] +
(-0.004836443728006368+0j) [X2 Y3 Y5 X6] +
(0.002236686658236843+0j) [X2 Z3 X4] +
(0.0067277788331757665+0j) [X2 Z3 Z5 X6] +
(0.0067277788331757665+0j) [X2 Z3 X6] +
(0.002236686658236843+0j) [X2 X4 Z5] +
(0.000276346968974246+0j) [Y2 X3 X4 Y5 Z6] +
(0.00934468360804178+0j) [Y2 X3 Y4 X5] +
(-0.004836443728006368+0j) [Y2 X3 Z4 Y5 X6] +
(-0.00473907074718689+0j) [Y2 Y3 X4 X5] +
(-0.004560096759032121+0j) [Y2 Y3 X4 X5 Z6] +
(0.00032184554262421473+0j) [Y2 Y3 Y4 Y5] +
(-0.004836443728006368+0j) [Y2 Y3 Y5 Y6] +
(0.002236686658236843+0j) [Y2 Z3 Y4] +
(0.0067277788331757665+0j) [Y2 Z3 Z5 Y6] +
(0.0067277788331757665+0j) [Y2 Z3 Y6] +
(0.002236686658236843+0j) [Y2 Y4 Z5] +
(0.02623048926468108+0j) [Z2] +
(-0.00

### Can remove these terms from Anstz

In [14]:
reduced_ijab_CC = ansatz_obj.Remove_indices_from_CC_qubit_operators(Qubit_Op_list_Second_Quant_CC_Ops_ijab,
                                                             indices_to_Remove)
reduced_ijab_CC

[0.125j [X2 Z3 Y4] +
 0.125j [X2 Z3 Y4 Z5] +
 0.125j [X2 Y4] +
 0.125j [X2 Y4 Z5] +
 -0.125j [Y2 Z3 X4] +
 -0.125j [Y2 Z3 X4 Z5] +
 -0.125j [Y2 X4] +
 -0.125j [Y2 X4 Z5],
 0.125j [X2 Z3 X4 Y5 Z6] +
 0.125j [X2 Z3 Y4 X5] +
 0.125j [X2 X4 Y5 Z6] +
 0.125j [X2 Y4 X5] +
 -0.125j [Y2 Z3 X4 X5] +
 0.125j [Y2 Z3 Y4 Y5 Z6] +
 -0.125j [Y2 X4 X5] +
 0.125j [Y2 Y4 Y5 Z6],
 0.125j [X2 Z3 Z5 Y6] +
 0.125j [X2 Z3 Y6] +
 0.125j [X2 Z5 Y6] +
 0.125j [X2 Y6] +
 -0.125j [Y2 Z3 Z5 X6] +
 -0.125j [Y2 Z3 X6] +
 -0.125j [Y2 Z5 X6] +
 -0.125j [Y2 X6]]

In [15]:
reduced_ia_CC = ansatz_obj.Remove_indices_from_CC_qubit_operators(Qubit_Op_list_Second_Quant_CC_Ops_ia,
                                                             indices_to_Remove)
reduced_ia_CC

[0.5j [X2 Y3 X4] +
 0.5j [Y2 Y3 Y4],
 0.5j [X2 Y3 Z5 X6] +
 0.5j [Y2 Y3 Z5 Y6],
 0.5j [Z2 Y3 Z4 X5] +
 -0.5j [X3 Y5],
 0.5j [Z2 Y3 Z5 Z6] +
 -0.5j [Y3]]

# NEXT need to re-label everything

In [16]:
# Relabelling H
relabel_dict, relabelled_reduced_Qubit_Hamiltonian = ansatz_obj.Re_label_Hamiltonian(reduced_Qubit_Hamiltonian)

print('qubit relabelling dict = ', relabel_dict)

relabelled_reduced_Qubit_Hamiltonian

qubit relabelling dict =  {2: 0, 3: 1, 4: 2, 5: 3, 6: 4}


(-7.27686951249773+0j) [] +
(0.00934468360804178+0j) [X0 X1 X2 X3] +
(-0.000276346968974246+0j) [X0 X1 Y2 Y3 Z4] +
(0.004836443728006368+0j) [X0 X1 Z2 Y3 Y4] +
(0.00032184554262421473+0j) [X0 Y1 X2 Y3] +
(0.00473907074718689+0j) [X0 Y1 Y2 X3] +
(0.004560096759032121+0j) [X0 Y1 Y2 X3 Z4] +
(-0.004836443728006368+0j) [X0 Y1 Y3 X4] +
(0.002236686658236843+0j) [X0 Z1 X2] +
(0.0067277788331757665+0j) [X0 Z1 Z3 X4] +
(0.0067277788331757665+0j) [X0 Z1 X4] +
(0.002236686658236843+0j) [X0 X2 Z3] +
(0.000276346968974246+0j) [Y0 X1 X2 Y3 Z4] +
(0.00934468360804178+0j) [Y0 X1 Y2 X3] +
(-0.004836443728006368+0j) [Y0 X1 Z2 Y3 X4] +
(-0.00473907074718689+0j) [Y0 Y1 X2 X3] +
(-0.004560096759032121+0j) [Y0 Y1 X2 X3 Z4] +
(0.00032184554262421473+0j) [Y0 Y1 Y2 Y3] +
(-0.004836443728006368+0j) [Y0 Y1 Y3 Y4] +
(0.002236686658236843+0j) [Y0 Z1 Y2] +
(0.0067277788331757665+0j) [Y0 Z1 Z3 Y4] +
(0.0067277788331757665+0j) [Y0 Z1 Y4] +
(0.002236686658236843+0j) [Y0 Y2 Z3] +
(0.02623048926468108+0j) [Z0] +
(-0.00

In [17]:
# Relabelling ANSATZ
relabelled_reduced_ia_CC = ansatz_obj.Re_label_CC_qubit_operators(relabel_dict, reduced_ia_CC)
relabelled_reduced_ijab_CC = ansatz_obj.Re_label_CC_qubit_operators(relabel_dict, reduced_ijab_CC)
relabelled_reduced_ijab_CC

[0.125j [X0 Z1 Y2] +
 0.125j [X0 Z1 Y2 Z3] +
 0.125j [X0 Y2] +
 0.125j [X0 Y2 Z3] +
 -0.125j [Y0 Z1 X2] +
 -0.125j [Y0 Z1 X2 Z3] +
 -0.125j [Y0 X2] +
 -0.125j [Y0 X2 Z3],
 0.125j [X0 Z1 X2 Y3 Z4] +
 0.125j [X0 Z1 Y2 X3] +
 0.125j [X0 X2 Y3 Z4] +
 0.125j [X0 Y2 X3] +
 -0.125j [Y0 Z1 X2 X3] +
 0.125j [Y0 Z1 Y2 Y3 Z4] +
 -0.125j [Y0 X2 X3] +
 0.125j [Y0 Y2 Y3 Z4],
 0.125j [X0 Z1 Z3 Y4] +
 0.125j [X0 Z1 Y4] +
 0.125j [X0 Z3 Y4] +
 0.125j [X0 Y4] +
 -0.125j [Y0 Z1 Z3 X4] +
 -0.125j [Y0 Z1 X4] +
 -0.125j [Y0 Z3 X4] +
 -0.125j [Y0 X4]]

## Find New input state

In [18]:
print('old input = ', ansatz_obj.Get_BK_HF_state_in_OCC_basis())
print('BUT following indices removed:', indices_to_Remove)
ansatz_obj.New_BK_HF_state(indices_to_Remove)

old input =  [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
BUT following indices removed: [0, 1, 7, 8, 9, 10, 11]


array([1., 0., 0., 0., 0.])

# Find what new FCI energy is

In [19]:
new_Molecular_H_MATRIX = Hamilt.Get_sparse_Qubit_Hamiltonian_matrix(relabelled_reduced_Qubit_Hamiltonian)


from scipy.linalg import eig
eig_values, eig_vectors = eig(new_Molecular_H_MATRIX.todense())
new_FCI_Energy = min(eig_values)


print('new_FCI = ', new_FCI_Energy, 'VS old FCI:', Hamilt.molecule.fci_energy)

new_FCI =  (-7.85968979457892+0j) VS old FCI: -7.8756525649279085


# Simulating

### Ansatz circuit 

In [20]:
import random
theta_ia_random_input = [random.uniform(0, 2*np.pi) for _ in range(len(relabelled_reduced_ia_CC))]
theta_ijab_random_input = [random.uniform(0, 2*np.pi) for _ in range(len(relabelled_reduced_ijab_CC))]
#combined_ia_ijab_theta_random_input = [*theta_ia_random_input, *theta_ijab_random_input]

In [21]:
new_BK_state = ansatz_obj.New_BK_HF_state(indices_to_Remove)


UCCSD_ansatz_Q_Circ_obj = Ansatz_Circuit(new_BK_state,
                                     relabelled_reduced_ia_CC, 
                                     relabelled_reduced_ijab_CC)

UCCSD_ansatz_Q_Circ = UCCSD_ansatz_Q_Circ_obj.Get_Full_HF_UCCSD_QC(
                                        Theta_param_list_ia=theta_ia_random_input, 
                                         Theta_param_list_ijab=theta_ijab_random_input,
                                         ia_first=True)
UCCSD_ansatz_Q_Circ

┌─────────┐                 ┌──────────┐
0: ───X───H──────────@─────────────────────────@───H───────────Rx(0.5π)───@─────────────────────────@───────────Rx(-0.5π)───H──────────@─────────────────────────────────@──────────H───────────Rx(0.5π)───@─────────────────────────────────────────@───Rx(-0.5π)──────────────@────────────────────────────────@─────────────────────────────────────────────────────────────────────@─────────────────────────────────@───H────────────────────@────────────────────────────@────H───────────H──────────@─────────────────────────@───────────H───Rx(0.5π)───@────────────────@───Rx(-0.5π)───Rx(0.5π)───@────────────────────────@───Rx(-0.5π)───Rx(0.5π)───@────────────────────────@───Rx(-0.5π)───Rx(0.5π)───@────────────────────────────────@───Rx(-0.5π)───H───@─────────────────────────@───H───────────H──────────@────────────────────────────────────────@───────────H───H───@─────────────────────────────────@───────────H──────────H───@─────────────────────────────────────────────────@──────────H──────────Rx(0.5π)───@─────────────────────────────────@───────────Rx(-0.5π)───Rx(0.5π)───@────────────────────────────────────────────────────────@───────────Rx(-0.5π)───Rx(0.5π)───@────────────────────────────────@───Rx(-0.5π)───Rx(0.5π)───@────────────────────────@───Rx(-0.5π)───H──────────@─────────────────────────────────@───────────H──────────H───@─────────────────────────@───H───────────H───@─────────────────@───H───────────H──────────@─────────────────────────@───────────H───Rx(0.5π)───@────────────────@───Rx(-0.5π)───Rx(0.5π)───@────────────────────────@───Rx(-0.5π)───Rx(0.5π)───@────────────────────────────────@───Rx(-0.5π)───Rx(0.5π)───@────────────────────────@───Rx(-0.5π)───H───@─────────────────────────────────────────@──────────H───H───@─────────────────────────@───────────H───
                     │                         │                          │                         │                                  │                                 │                                 │                                         │                          │                                │                                                                     │                                 │                        │                            │                           │                         │                          │                │                          │                        │                          │                        │                          │                                │                   │                         │                          │                                        │                   │                                 │                          │                                                 │                                │                                 │                                  │                                                        │                                  │                                │                          │                        │                          │                                 │                          │                         │                   │                 │                          │                         │                          │                │                          │                        │                          │                                │                          │                        │                   │                                         │                  │                         │
1: ───I───Rx(0.5π)───X───@─────────────────@───X───Rx(-0.5π)───Rx(0.5π)───X───@─────────────────@───X───────────Rx(-0.5π)───Rx(0.5π)───X───@─────────────────────────@───X──────────Rx(-0.5π)───Rx(0.5π)───X───@─────────────────────────@───────────X───Rx(-0.5π)───Rx(0.5π)───X───@────────────────────────@───X──────────Rx(-0.5π)───H───@───────────────@───H───────────Rx(0.5π)───X───@──────────────────────

### Calc ENERGY 

In [22]:
Hamiltonian_graph_obj = Openfermion_Hamiltonian_Graph(relabelled_reduced_Qubit_Hamiltonian)

commutativity_flag = 'AC' ## <- defines relationship between sets!!!
plot_graph = False
Graph_colouring_strategy='largest_first'
anti_commuting_sets = Hamiltonian_graph_obj.Get_Clique_Cover_as_QubitOp(commutativity_flag, Graph_colouring_strategy=Graph_colouring_strategy, plot_graph=plot_graph)
anti_commuting_sets

Building Graph Edges: 100%|##########| 62/62 [00:00<00:00, 393.01it/s]


{0: [(-7.27686951249773+0j) []],
 1: [(0.07828114149315556+0j) [Z1 Z3]],
 2: [(0.05937749358221965+0j) [Z0 Z2],
  (0.0067277788331757665+0j) [X0 Z1 Z3 X4],
  (0.004836443728006367+0j) [Z0 X1 Y2 Y3 X4],
  (0.01059579775705475+0j) [Z1 Y2 Z3 Y4],
  (0.004836443728006368+0j) [X0 X1 Z2 Y3 Y4]],
 3: [(-0.1443201912269884+0j) [Z4],
  (0.01059579775705475+0j) [X2 Z3 X4],
  (-0.004836443728006367+0j) [X1 X2 X3 X4],
  (0.0067277788331757665+0j) [Y0 Z1 Z3 Y4]],
 4: [(-0.1443201912269884+0j) [Z1 Z3 Z4],
  (0.0067277788331757665+0j) [X0 Z1 X4],
  (0.01059579775705475+0j) [Y2 Z3 Y4],
  (-0.004836443728006368+0j) [Y0 Y1 Y3 Y4]],
 5: [(0.05937749358221965+0j) [Z0 Z1 Z2 Z3],
  (-0.004836443728006367+0j) [X1 Y2 X3 Y4],
  (-0.004836443728006368+0j) [Y0 X1 Z2 Y3 X4]],
 6: [(0.06848948156783816+0j) [Z0 Z4],
  (-0.004560096759032121+0j) [Y0 Y1 X2 X3 Z4],
  (0.01059579775705475+0j) [Z1 X2 Z3 X4]],
 7: [(0.07521726040101392+0j) [Z0 Z1 Z3 Z4],
  (0.004560096759032121+0j) [X0 Y1 Y2 X3 Z4],
  (-0.004836443728006

In [23]:
from quchem.LCU_method import *
from quchem.Unitary_partitioning import * 
from quchem.quantum_circuit_functions import *

In [24]:
def Get_pauli_matrix(PauliOp, N_system_qubits):
    
    pauliDict=   {'X':np.array([[0,1],[1,0]]),
                          'Y':np.array([[0,-1j],[1j,0]]),
                          'Z':np.array([[1,0],[0,-1]]),
                          'I': np.eye(2)}
    
    list_Q_nos, list_P_strs = list(zip(*[Paulistrs for Paulistrs, const in PauliOp.terms.items()][0]))

    list_of_ops = []
    for i in range(N_system_qubits):
        if i in list_Q_nos:
            index = list_Q_nos.index(i)
            list_of_ops.append(pauliDict[list_P_strs[index]])
        else:
            list_of_ops.append(pauliDict['I'])

    matrix = reduce(kron, list_of_ops)

    return matrix

In [25]:
#Get_state_as_str(n_qubits, qubit_state_int)
Get_state_as_str(3,1)


qubit_state_dict = {
                        0:np.array([[1],[0]]),
                        1:np.array([[0],[1]])
                        }


In [26]:
state1 = reduce(np.kron, [qubit_state_dict[0], qubit_state_dict[0], qubit_state_dict[0]])
state2 = reduce(np.kron, [qubit_state_dict[1], qubit_state_dict[1], qubit_state_dict[1]])

system_state = 1/np.sqrt(2)* (state1 + state2)

print(system_state)


dm = system_state.dot(system_state.conj().transpose())
# print(dm)
print('')

systemA=2**1 # 1 qubit
systemB=2**2 # 2 qubits
reshaped_dm = dm.reshape([systemA, systemB, systemA, systemB])

print('systemA:',np.einsum('jiki->jk', reshaped_dm))
print('')
print('systemB:', np.einsum('ijik->jk', reshaped_dm))


### my way

# print(dm.shape)
I_system_A = np.eye((systemA))
# I_system_A = np.ones((systemA, 1))
basis_B = np.eye((systemB))

# print(I_system_A)
# print(basis_B)

reduced_dm= np.zeros((systemA, systemA))
for b in range(basis_B.shape[0]):
    b_ket = basis_B[b,:].reshape([systemB,1])
    I_a_b_ket = np.kron(I_system_A, b_ket)
    I_a_b_bra=I_a_b_ket.transpose().conj()

    term = I_a_b_bra.dot(dm.dot(I_a_b_ket))
    reduced_dm+= term
print(reduced_dm)


# print(dm.shape)
I_system_B = np.eye((systemB))
# I_system_A = np.ones((systemA, 1))
basis_A = np.eye(systemA)

reduced_dm= np.zeros((systemB, systemB))
for b in range(basis_A.shape[0]):
    b_ket = basis_A[b,:].reshape([systemA, 1])
    I_a_b_ket = np.kron(I_system_B, b_ket)
    I_a_b_bra=I_a_b_ket.transpose().conj()

    term = I_a_b_bra.dot(dm.dot(I_a_b_ket))
    reduced_dm+= term
    
print(reduced_dm)

[[0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.70710678]]

systemA: [[0.5 0. ]
 [0.  0.5]]

systemB: [[0.5 0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
[[0.5 0. ]
 [0.  0.5]]
[[0.5 0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]


In [27]:
# # https://github.com/stephenhky/pyqentangle/blob/master/pyqentangle/schmidt.py
# def schmidt_decomposition_numpy(bipartitepurestate_tensor):
#     """ Calculate the Schmidt decomposition of the given discrete bipartite quantum system
#     This is called by :func:`schmidt_decomposition`. This runs numpy.
#     :param bipartitepurestate_tensor: tensor describing the bi-partitite states, with each elements the coefficients for :math:`|ij\\rangle`
#     :return: list of tuples containing the Schmidt coefficient, eigenmode for first subsystem, and eigenmode for second subsystem
#     :type bipartitepurestate_tensor: numpy.ndarray
#     :rtype: list
#     """
#     state_dims = bipartitepurestate_tensor.shape
#     mindim = np.min(state_dims)

#     vecs1, diags, vecs2_h = np.linalg.svd(bipartitepurestate_tensor)
#     vecs2 = vecs2_h.transpose()

#     decomposition = [(diags[k], vecs1[:, k], vecs2[:, k])
#                      for k in range(mindim)]

#     decomposition = sorted(decomposition, key=lambda dec: dec[0], reverse=True)

#     return decomposition
# schmidt_decomposition_numpy(system_state)

In [28]:
def Calc_Pauli_expect_of_set_LCU(theta_ia_ijab, Pn_index, anti_commuting_set):
    
    R_uncorrected, Pn, gamma_l = Get_R_op_list(anti_commuting_set, Pn_index, check_operator=True)
    R_corrected_Op_list, R_corr_list, ancilla_amplitudes, l1_norm = absorb_complex_phases(R_uncorrected)
    
    theta_ia=theta_ia_ijab[:len(relabelled_reduced_ia_CC)]
    theta_ijab=theta_ia_ijab[len(relabelled_reduced_ia_CC):]
    
    ansatz_circuit = UCCSD_ansatz_Q_Circ_obj.Get_Full_HF_UCCSD_QC(
                                        Theta_param_list_ia=theta_ia, 
                                         Theta_param_list_ijab=theta_ijab,
                                         ia_first=True)
    
    LCU_Q_circuit = Full_Ansatz_and_Quantum_R_circuit(Pn,
                                   R_corrected_Op_list,
                                   R_corr_list,
                                   ancilla_amplitudes,
                                   Hamilt.molecule.n_qubits,
                                   ansatz_circuit)
    
    # ancilla line check!
    N_ancilla_qubits = int(np.ceil(np.log2(len(ancilla_amplitudes))))
    ancilla_obj = prepare_arb_state(ancilla_amplitudes, N_ancilla_qubits)
    ancilla_circ = ancilla_obj.Get_state_prep_Circuit()
    simulator = cirq.Simulator()
    output_ket = simulator.compute_amplitudes(ancilla_circ,
                                          bitstrings=[i for i in range(2 ** N_ancilla_qubits)])
#     print(output_ket[:len(ancilla_amplitudes)])
#     print(ancilla_amplitudes)
#     print(np.allclose(ancilla_amplitudes, output_ket[:len(ancilla_amplitudes)]))
    if not (np.allclose(ancilla_amplitudes, output_ket[:len(ancilla_amplitudes)])):
        raise ValueError('ancilla mistake')
    # ancilla line check!
    
    
    input_state = [np.array([[1], [0]]) for _ in range(len(LCU_Q_circuit.all_qubits()))]
    input_ket = reduce(kron, input_state)
    circuit_matrix = LCU_Q_circuit.unitary()

#     print(LCU_Q_circuit.to_text_diagram(transpose=True))
    
    ansatz_state_ket = circuit_matrix.dot(input_ket.todense())

    full_density_matrix = np.outer(ansatz_state_ket, ansatz_state_ket)


    ## First project state onto all zero ancilla state using POVM
    n_qubits = len(LCU_Q_circuit.all_qubits())
    n_ancilla = int(np.ceil(np.log2(len(ancilla_amplitudes))))
    N_system_qubits = n_qubits - n_ancilla

    I_system_operator = np.eye((2**N_system_qubits))
    ancilla_0_state_list = [np.array([[1], [0]]) for _ in range(n_ancilla)]
    ancilla_0_state = reduce(np.kron, ancilla_0_state_list)
    ancilla_0_projector = np.outer(ancilla_0_state, ancilla_0_state)

    POVM_0_ancilla = np.kron(I_system_operator, ancilla_0_projector)
    Kraus_Op_0 = POVM_0_ancilla.copy()

    term = Kraus_Op_0.dot(full_density_matrix.dot(Kraus_Op_0.transpose().conj()))
    projected_density_matrix = term/np.trace(term) # projected into correct space using POVM ancilla measurement!

    ## Next get partial density matrix over system qubits # aka partial trace!
    # https://scicomp.stackexchange.com/questions/27496/calculating-partial-trace-of-array-in-numpy
    
    # reshape to do the partial trace easily using np.einsum
    reshaped_dm = projected_density_matrix.reshape([2 ** N_system_qubits, 2 ** n_ancilla,
                                                    2 ** N_system_qubits, 2 ** n_ancilla])
    reduced_dm = np.einsum('jiki->jk', reshaped_dm)
    
    
    H_sub_term_matrix = Get_pauli_matrix(Pn, N_system_qubits)

#     from openfermion import qubit_operator_sparse
#     mat =  qubit_operator_sparse(Pn, n_qubits=N_system_qubits)
    
    energy = np.trace(reduced_dm.dot(H_sub_term_matrix.todense()))
    return (energy * gamma_l).real


Pn_index=2
set_index=2

# theta_ia_random_input = [random.uniform(0, 2*np.pi) for _ in range(len(relabelled_reduced_ia_CC))]
# theta_ijab_random_input = [random.uniform(0, 2*np.pi) for _ in range(len(relabelled_reduced_ijab_CC))]
combined_ia_ijab_theta_random_input = [*theta_ia_random_input, *theta_ijab_random_input]
Calc_Pauli_expect_of_set_LCU(combined_ia_ijab_theta_random_input, Pn_index, anti_commuting_sets[set_index])

Pn= R*H_n*R_dag 
Pn= 1 [Z0 X1 Y2 Y3 X4]
R*H_n*R_dag =  (1.0000000000000002+0j) [Z0 X1 Y2 Y3 X4]


-0.026987308042019077

In [29]:
set_index=2
N_index = 0
##
R_linear_comb_list, Pn, gamma_l = Get_R_op_list(anti_commuting_sets[set_index], N_index)
R_corrected_Op_list, phase_corr, ancilla_amplitudes, l1 = absorb_complex_phases(R_linear_comb_list)


### circuit
n_anilla_qubits = int(np.ceil(np.log2(len(ancilla_amplitudes))))
No_system_qubits = len(UCCSD_ansatz_Q_Circ.all_qubits())

R_circ_obj = LCU_R_gate(n_anilla_qubits, No_system_qubits, R_corrected_Op_list, phase_corr, Pn)
R_circ_circ = cirq.Circuit(
    cirq.decompose_once((R_circ_obj(*cirq.LineQubit.range(R_circ_obj.num_qubits())))))

print(R_circ_circ)

print('')
print(phase_corr)
print(R_corrected_Op_list)
print('Pn', Pn)

0: ───1*I0───1j*Y0───I────────────(-0-1j)*Z0───1j*Y0───
      │      │       │            │            │
1: ───┼──────Z1──────X1───────────Z1───────────X1──────
      │      │       │            │            │
2: ───┼──────Z2──────(-0-1j)*X2───X2───────────I───────
      │      │       │            │            │
3: ───┼──────Z3──────Y3───────────Z3───────────Y3──────
      │      │       │            │            │
4: ───┼──────X4──────X4───────────Y4───────────Y4──────
      │      │       │            │            │
5: ───(0)────(0)─────(0)──────────(0)──────────@───────
      │      │       │            │            │
6: ───(0)────(0)─────@────────────@────────────(0)─────
      │      │       │            │            │
7: ───(0)────@───────(0)──────────@────────────(0)─────

[1, 1j, (-0-1j), (-0-1j), 1j]
[0.90382974933729 [], 0.21360766820124474 [Y0 Z1 Z2 Z3 X4], 0.18111067769199077 [X1 X2 Y3 X4], 0.26806975426260654 [Z0 Z1 X2 Z3 Y4], 0.1811106776919908 [Y0 X1 Y3 Y4]]
Pn 1 [Z0 Z2

In [30]:
def Calc_Pauli_expect_of_set_LCU(theta_ia_ijab, Pn_index, anti_commuting_set):
    
    R_uncorrected, Pn, gamma_l = Get_R_op_list(anti_commuting_set, Pn_index, check_operator=True)
    R_corrected_Op_list, R_corr_list, ancilla_amplitudes, l1_norm = absorb_complex_phases(R_uncorrected)
    
    theta_ia=theta_ia_ijab[:len(relabelled_reduced_ia_CC)]
    theta_ijab=theta_ia_ijab[len(relabelled_reduced_ia_CC):]
    
    ansatz_circuit = UCCSD_ansatz_Q_Circ_obj.Get_Full_HF_UCCSD_QC(
                                        Theta_param_list_ia=theta_ia, 
                                         Theta_param_list_ijab=theta_ijab,
                                         ia_first=True)
    
    LCU_Q_circuit = Full_Ansatz_and_Quantum_R_circuit(Pn,
                                   R_corrected_Op_list,
                                   R_corr_list,
                                   ancilla_amplitudes,
                                   Hamilt.molecule.n_qubits,
                                   ansatz_circuit)
    
    # ancilla line check!
    N_ancilla_qubits = int(np.ceil(np.log2(len(ancilla_amplitudes))))
    ancilla_obj = prepare_arb_state(ancilla_amplitudes, N_ancilla_qubits)
    ancilla_circ = ancilla_obj.Get_state_prep_Circuit()
    simulator = cirq.Simulator()
    output_ket = simulator.compute_amplitudes(ancilla_circ,
                                          bitstrings=[i for i in range(2 ** N_ancilla_qubits)])
#     print(output_ket[:len(ancilla_amplitudes)])
#     print(ancilla_amplitudes)
#     print(np.allclose(ancilla_amplitudes, output_ket[:len(ancilla_amplitudes)]))
    if not (np.allclose(ancilla_amplitudes, output_ket[:len(ancilla_amplitudes)])):
        raise ValueError('ancilla mistake')
    # ancilla line check!
    
    
    input_state = [np.array([[1], [0]]) for _ in range(len(LCU_Q_circuit.all_qubits()))]
    input_ket = reduce(kron, input_state)
    circuit_matrix = LCU_Q_circuit.unitary()

#     print(LCU_Q_circuit.to_text_diagram(transpose=True))
    
    ansatz_state_ket = circuit_matrix.dot(input_ket.todense())

    full_density_matrix = np.outer(ansatz_state_ket, ansatz_state_ket)


    ## First project state onto all zero ancilla state using POVM
    n_qubits = len(LCU_Q_circuit.all_qubits())
    n_ancilla = int(np.ceil(np.log2(len(ancilla_amplitudes))))
    N_system_qubits = n_qubits - n_ancilla

    I_system_operator = np.eye((2**N_system_qubits))
    ancilla_0_state_list = [np.array([[1], [0]]) for _ in range(n_ancilla)]
    ancilla_0_state = reduce(np.kron, ancilla_0_state_list)
    ancilla_0_projector = np.outer(ancilla_0_state, ancilla_0_state)

    POVM_0_ancilla = np.kron(I_system_operator, ancilla_0_projector)
    Kraus_Op_0 = POVM_0_ancilla.copy()

    term = Kraus_Op_0.dot(full_density_matrix.dot(Kraus_Op_0.transpose().conj()))
    projected_density_matrix = term/np.trace(term) # projected into correct space using POVM ancilla measurement!

    ## Next get partial density matrix over system qubits # aka partial trace!
    # https://scicomp.stackexchange.com/questions/27496/calculating-partial-trace-of-array-in-numpy
    
    # reshape to do the partial trace easily using np.einsum
#     reshaped_dm = projected_density_matrix.reshape([2 ** N_system_qubits, 2 ** n_ancilla,
#                                                     2 ** N_system_qubits, 2 ** n_ancilla])
#     reduced_dm = np.einsum('jiki->jk', reshaped_dm)
    

    ### taking partial trace
    # p_a = sum_{b} (I*<b|) p_{ab} (I*|b>)
    
    basis_ancilla = np.eye((2**n_ancilla))
    reduced_dm= np.zeros((2**N_system_qubits, 2**N_system_qubits), dtype=complex)
    for b in range(basis_ancilla.shape[0]):
        b_ket = basis_ancilla[b,:].reshape([2**n_ancilla,1])
        I_a_b_ket = np.kron(I_system_operator, b_ket)
        I_a_b_bra=I_a_b_ket.transpose().conj()

        term = I_a_b_bra.dot(projected_density_matrix.dot(I_a_b_ket))
        reduced_dm+= term
      
    H_sub_term_matrix = Get_pauli_matrix(Pn, N_system_qubits)
   
    energy = np.trace(reduced_dm.dot(H_sub_term_matrix.todense()))
    return (energy * gamma_l).real


Pn_index=3
set_index=4

# theta_ia_random_input = [random.uniform(0, 2*np.pi) for _ in range(len(relabelled_reduced_ia_CC))]
# theta_ijab_random_input = [random.uniform(0, 2*np.pi) for _ in range(len(relabelled_reduced_ijab_CC))]
combined_ia_ijab_theta_random_input = [*theta_ia_random_input, *theta_ijab_random_input]
Calc_Pauli_expect_of_set_LCU(combined_ia_ijab_theta_random_input, Pn_index, anti_commuting_sets[set_index])

Pn= R*H_n*R_dag 
Pn= 1 [Y0 Y1 Y3 Y4]
R*H_n*R_dag =  (0.9999999999999997+0j) [Y0 Y1 Y3 Y4]


0.011406322167912406

In [37]:
def Calc_Pauli_expect_of_set_CONJ(theta_ia_ijab, PS_index, anti_commuting_set):
       
    theta_ia=theta_ia_ijab[:len(relabelled_reduced_ia_CC)]
    theta_ijab=theta_ia_ijab[len(relabelled_reduced_ia_CC):]
    
    ansatz_circuit = UCCSD_ansatz_Q_Circ_obj.Get_Full_HF_UCCSD_QC(
                                        Theta_param_list_ia=theta_ia, 
                                         Theta_param_list_ijab=theta_ijab,
                                         ia_first=True)
    

    CONJ_Q_circuit, Ps, gamma_l = Generate_Full_Q_Circuit_Conj_NO_M_gates(ansatz_circuit,
                                                                 anti_commuting_set,
                                                                 PS_index,
                                                                 check_reduction=True)
    
    
#     print(CONJ_Q_circuit.to_text_diagram(transpose=True))
    
    input_state = [np.array([[1], [0]]) for _ in range(len(CONJ_Q_circuit.all_qubits()))]
    input_ket = reduce(kron, input_state)
    circuit_matrix = CONJ_Q_circuit.unitary()

    ansatz_state_ket = circuit_matrix.dot(input_ket.todense())
    
    ansatz_state_bra = ansatz_state_ket.transpose().conj()
    H_sub_term_matrix = Get_pauli_matrix(Ps, len(CONJ_Q_circuit.all_qubits()))
    
    energy = ansatz_state_bra.dot(H_sub_term_matrix.dot(ansatz_state_ket))
    
    
    return (energy.item(0) * gamma_l).real


PS_index=0
set_index=8
# theta_ia_random_input = [random.uniform(0, 2*np.pi) for _ in range(len(relabelled_reduced_ia_CC))]
# theta_ijab_random_input = [random.uniform(0, 2*np.pi) for _ in range(len(relabelled_reduced_ijab_CC))]
combined_ia_ijab_theta_random_input = [*theta_ia_random_input, *theta_ijab_random_input]

Calc_Pauli_expect_of_set_CONJ(combined_ia_ijab_theta_random_input, PS_index, anti_commuting_sets[set_index])

-0.0035072506741096435

In [32]:
fasdfads

NameError: name 'fasdfads' is not defined

In [ ]:
anti_commuting_sets[8]

In [ ]:
H_S = QubitOperator()
for QubitOp in anti_commuting_sets[8]:
    H_S += QubitOp

##
unique_qubits = set()
for PauliOp, const in H_S.terms.items():
    qubitNo, _ = zip(*list(PauliOp))
    unique_qubits.update(qubitNo)
unique_qubits

In [ ]:
Rs_circ,Ps,gamma = Build_reduction_circuit(anti_commuting_sets[8], 0, check_reduction=False)
Rs_circ

In [ ]:
qbits = [cirq.LineQubit(i) for i in unique_qubits]
Rs_circ.unitary(qubits_that_should_be_present=qbits).shape

In [ ]:
Ps_mat = Get_pauli_matrix(Ps, len([cirq.LineQubit(i) for i in unique_qubits]))
Ps_mat.shape

In [ ]:
Ps

In [ ]:
Ps_mat = Get_pauli_matrix(Ps, len([cirq.LineQubit(i) for i in unique_qubits]))
Ps_mat.shape

In [ ]:

qbits = cirq.LineQubit.range(int(np.log2(qubit_operator_sparse(H_S).todense().shape[0])))
Rs_circ.unitary(qubits_that_should_be_present=qbits).shape
Ps_mat = Get_pauli_matrix(Ps, len(qbits))
Ps_mat.shape

In [ ]:
X_sk_theta_sk_list, full_normalised_set, Ps, gamma_l = Get_Xsk_op_list(anti_commuting_sets[8], 0)
X_sk_theta_sk_list

In [ ]:
max([lineQubit.x for lineQubit in list(Rs_circ.all_qubits())])+1

In [ ]:
# X_sk_theta_sk_list, full_normalised_set, Ps, gamma_l = Get_Xsk_op_list(anti_commuting_sets[8], 0)

# Rs_circ,Ps,gamma = Build_reduction_circuit(anti_commuting_sets[8], 0, check_reduction=False)

# R_S_matrix = Rs_circ.unitary()

# H_S =QubitOperator()
# for QubitOp in full_normalised_set['PauliWords']:
#     H_S+=QubitOp
# from openfermion import qubit_operator_sparse
# H_S_matrix = qubit_operator_sparse(H_S, n_qubits=5)

# Ps_mat = Get_pauli_matrix(Ps, 5)

# # reduction_mat = R_S_matrix.dot(H_S_matrix.dot(R_S_matrix.conj().transpose()))

In [38]:
def Calc_Pauli_expect_of_set_standard(theta_ia_ijab, PauliWord):
    
    if list(PauliWord.terms.keys())[0] ==():
        factor = list(PauliWord.terms.values())[0]
        return factor
    else:
        theta_ia=theta_ia_ijab[:len(relabelled_reduced_ia_CC)]
        theta_ijab=theta_ia_ijab[len(relabelled_reduced_ia_CC):]

        ansatz_circuit = UCCSD_ansatz_Q_Circ_obj.Get_Full_HF_UCCSD_QC(
                                        Theta_param_list_ia=theta_ia, 
                                         Theta_param_list_ijab=theta_ijab,
                                         ia_first=True)

        input_state = [np.array([[1], [0]]) for _ in range(len(ansatz_circuit.all_qubits()))]
        input_ket = reduce(kron, input_state)
        circuit_matrix = ansatz_circuit.unitary()

        ansatz_state_ket = circuit_matrix.dot(input_ket.todense())
        ansatz_state_bra = ansatz_state_ket.transpose().conj()

        H_sub_term_matrix = Get_pauli_matrix(PauliWord, len(ansatz_circuit.all_qubits()))

        exp = ansatz_state_bra.dot(H_sub_term_matrix.dot(ansatz_state_ket))
        factor = list(PauliWord.terms.values())[0]

        energy = (exp.item(0) * factor)

        return energy.real
    
# theta_ia_random_input = [random.uniform(0, 2*np.pi) for _ in range(len(relabelled_reduced_ia_CC))]
# theta_ijab_random_input = [random.uniform(0, 2*np.pi) for _ in range(len(relabelled_reduced_ijab_CC))]
combined_ia_ijab_theta_random_input = [*theta_ia_random_input, *theta_ijab_random_input]
Calc_Pauli_expect_of_set_standard(combined_ia_ijab_theta_random_input, anti_commuting_sets[0][0])

(-7.27686951249773+0j)

In [39]:
set_index=3

E=0
for P in anti_commuting_sets[set_index]:
    E+= Calc_Pauli_expect_of_set_standard(combined_ia_ijab_theta_random_input, P)
E

-0.06654918302596306

In [40]:
def Standard_VQE(theta_ia_ijab):
    E_total=[]
    for PauliWord in relabelled_reduced_Qubit_Hamiltonian:
        e_partial = Calc_Pauli_expect_of_set_standard(theta_ia_ijab, PauliWord)
        E_total.append(e_partial)
    return sum(E_total)

Standard_VQE(combined_ia_ijab_theta_random_input)

(-7.271283632596182+0j)

In [41]:
def LCU_VQE(theta_ia_ijab, Pn_index=0):
    E_total=[]
    for anti_commuting_set in anti_commuting_sets.values():
        if len(anti_commuting_set)>1:
            LCU_E = Calc_Pauli_expect_of_set_LCU(theta_ia_ijab, Pn_index, anti_commuting_set)
            E_total.append(LCU_E)
#             print(LCU_E)
        else:
            PauliWord = anti_commuting_set[0]
            energy = Calc_Pauli_expect_of_set_standard(theta_ia_ijab, PauliWord)
            E_total.append(energy)
    return sum(E_total)
LCU_VQE(combined_ia_ijab_theta_random_input, Pn_index=1)

Pn= R*H_n*R_dag 
Pn= 1 [X0 Z1 Z3 X4]
R*H_n*R_dag =  (0.9999999999999998+0j) [X0 Z1 Z3 X4]
Pn= R*H_n*R_dag 
Pn= 1 [X2 Z3 X4]
R*H_n*R_dag =  (1.0000000000000002+0j) [X2 Z3 X4]
Pn= R*H_n*R_dag 
Pn= 1 [X0 Z1 X4]
R*H_n*R_dag =  (0.9999999999999999+0j) [X0 Z1 X4]
Pn= R*H_n*R_dag 
Pn= 1 [X1 Y2 X3 Y4]
R*H_n*R_dag =  (0.9999999999999998+0j) [X1 Y2 X3 Y4]
Pn= R*H_n*R_dag 
Pn= 1 [Y0 Y1 X2 X3 Z4]
R*H_n*R_dag =  (0.9999999999999997+0j) [Y0 Y1 X2 X3 Z4]
Pn= R*H_n*R_dag 
Pn= 1 [X0 Y1 Y2 X3 Z4]
R*H_n*R_dag =  (1+0j) [X0 Y1 Y2 X3 Z4]
Pn= R*H_n*R_dag 
Pn= 1 [Y1 Z2 Y3 Z4]
R*H_n*R_dag =  (1+0j) [Y1 Z2 Y3 Z4]
Pn= R*H_n*R_dag 
Pn= 1 [Z0 X1 X3 Z4]
R*H_n*R_dag =  (0.9999999999999998+0j) [Z0 X1 X3 Z4]
Pn= R*H_n*R_dag 
Pn= 1 [X1 Z2 X3]
R*H_n*R_dag =  (1+0j) [X1 Z2 X3]
Pn= R*H_n*R_dag 
Pn= 1 [Y0 Y1 X2 X3]
R*H_n*R_dag =  (1+0j) [Y0 Y1 X2 X3]
Pn= R*H_n*R_dag 
Pn= 1 [Z1 Z2 Z4]
R*H_n*R_dag =  (0.9999999999999998+0j) [Z1 Z2 Z4]
Pn= R*H_n*R_dag 
Pn= 1 [X1 Z2 X3 Z4]
R*H_n*R_dag =  (1+0j) [X1 Z2 X3 Z4]
Pn= R*H_n*R_dag 


(-7.271283632596181+0j)

In [44]:
def Conj_VQE(theta_ia_ijab, PS_index=0):
    E_total=[]
    for anti_commuting_set in anti_commuting_sets.values():
        if len(anti_commuting_set)>1:
            print(set_key)
            CONJ_E = Calc_Pauli_expect_of_set_CONJ(theta_ia_ijab, PS_index, anti_commuting_set)
            E_total.append(CONJ_E)
        else:
            energy = Calc_Pauli_expect_of_set_standard(theta_ia_ijab, anti_commuting_set[0])
            E_total.append(energy)
    return sum(E_total)
Conj_VQE(combined_ia_ijab_theta_random_input, PS_index=0)

NameError: name 'set_key' is not defined

## Optimizing