In [1]:
from quchem.Hamiltonian_Generator_Functions import *
from quchem.Graph import *
### HAMILTONIAN start
Molecule = 'LiH'
geometry = None # [('H', (0., 0., 0.)), ('H', (0., 0., 0.74))]
basis = 'sto-6g'


### Get Hamiltonian
Hamilt = Hamiltonian_PySCF(Molecule,
                     run_scf=1, run_mp2=1, run_cisd=1, run_ccsd=1, run_fci=1,
                     basis=basis,
                     multiplicity=1,
                     geometry=geometry)  # normally None!
QubitHamiltonian = Hamilt.Get_Qubit_Hamiltonian(threshold=None, transformation='BK')
### HAMILTONIAN end
QubitHamiltonian

(-3.9899724181893688+0j) [] +
(0.04037460325643171+0j) [X0 X1 X2] +
(-0.0031615876042052483+0j) [X0 X1 X2 X3 Y7 Y11] +
(0.0016204769263760675+0j) [X0 X1 X2 Y3 Y5] +
(0.003650850255675358+0j) [X0 X1 X2 Z3] +
(0.0018998726581458524+0j) [X0 X1 Z2 X3 Y7 Z9 Y10 X11] +
(0.004695260540245879+0j) [X0 X1 Z2 Y3 Y4 X5] +
(-0.0012113027134835635+0j) [X0 X1 X3 X4 Y7 Y11] +
(0.0010441957704832422+0j) [X0 X1 X3 Y4 Y5 Z6 Z7] +
(0.0012113027134835635+0j) [X0 X1 X3 Y4 Z5 Y7 Z9 Z10 X11] +
(0.0025594391105536424+0j) [X0 X1 X3 Z4 Y5 Y6 Z7] +
(6.648581206851742e-05+0j) [X0 X1 X3 Z4 Z5 Y7 Z9 Y10 X11] +
(0.0012777885255520814+0j) [X0 X1 X3 Z4 Y7 Z9 Y10 X11] +
(0.0009618499558327747+0j) [X0 X1 X3 X6 Y7 Y11] +
(-0.00015670172210402767+0j) [X0 X1 X3 Z6 Y7 Z9 Y10 X11] +
(0.0009618499558327743+0j) [X0 X1 X3 Y7 X8 Y11] +
(-0.0009618499558327743+0j) [X0 X1 X3 Y7 Y8 Z10 X11] +
(-0.00015670172210402648+0j) [X0 X1 X3 Y7 Z8 Z9 Y10 X11] +
(0.0008051482337287478+0j) [X0 X1 X3 Y7 Z8 Y10 X11] +
(0.015294910119291035+0j) [X0

In [2]:
from quchem.Ansatz_Generator_Functions import *


ansatz_obj = Ansatz(Hamilt.molecule.n_electrons, Hamilt.molecule.n_qubits)

print('JW ground state = ', ansatz_obj.Get_JW_HF_state_in_OCC_basis())
print('BK ground state = ', ansatz_obj.Get_BK_HF_state_in_OCC_basis())

JW ground state =  [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
BK ground state =  [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


The LiH ground state under JW is:

$$|\psi \rangle_{HF}^{ground} = | 1 1 1 1 \:  0 0 0 0 0 0 0 0 \rangle$$

and under BK is:

$$|\psi \rangle_{HF}^{ground} = | 1 0 1 0 0 0 0 0 0 0 0 0 \rangle$$

### Look at NATURAL orbital occupations!

In [3]:
NOON_spins_combined, NMO_basis = Hamilt.Get_NOON()
##
Hamilt.Get_CCSD_Amplitudes()

NOON_spins_combined

print(print(np.around(np.diag(NOON_spins_combined), 5)))

[[1.99992e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 1.96765e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 2.71800e-02 0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 2.59000e-03 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 2.59000e-03 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 8.00000e-05]]
None


This shows that orbitals (0,1) are nearly always FILLED
and
orbitals (10,11) are nearly always UNILLED!

In paper: PHYS. REV. X, **8**, 031022 (2018)
- active space chosen to be **spatial orbitals** 1-4 (aka spin orbital indices (2,3),(4,5),(6,7),(8,9)
- aka to simply problem here orbitals (8,9) also assumed to be empty!


In [4]:
from quchem.Ansatz_Generator_Functions import *


ansatz_obj = Ansatz(Hamilt.molecule.n_electrons, Hamilt.molecule.n_qubits)



Sec_Quant_CC_ops_ia, Sec_Quant_CC_ops_ijab, theta_parameters_ia, theta_parameters_ijab=ansatz_obj.Get_ia_and_ijab_terms(single_cc_amplitudes=None, 
                                                                                                             double_cc_amplitudes=None, 
                                                                                                             singles_hamiltonian=None,
                                                                                                             doubles_hamiltonian=None, 
                                                                                                             tol_filter_small_terms = None)

Sec_Quant_CC_ops_ia

[-1.0 [0^ 4] +
 1.0 [4^ 0],
 -1.0 [0^ 6] +
 1.0 [6^ 0],
 -1.0 [0^ 8] +
 1.0 [8^ 0],
 -1.0 [0^ 10] +
 1.0 [10^ 0],
 -1.0 [2^ 4] +
 1.0 [4^ 2],
 -1.0 [2^ 6] +
 1.0 [6^ 2],
 -1.0 [2^ 8] +
 1.0 [8^ 2],
 -1.0 [2^ 10] +
 1.0 [10^ 2],
 -1.0 [1^ 5] +
 1.0 [5^ 1],
 -1.0 [1^ 7] +
 1.0 [7^ 1],
 -1.0 [1^ 9] +
 1.0 [9^ 1],
 -1.0 [1^ 11] +
 1.0 [11^ 1],
 -1.0 [3^ 5] +
 1.0 [5^ 3],
 -1.0 [3^ 7] +
 1.0 [7^ 3],
 -1.0 [3^ 9] +
 1.0 [9^ 3],
 -1.0 [3^ 11] +
 1.0 [11^ 3]]

# Remove fermionic terms we are NOT taking into account

In [5]:
ansatz_obj = BK_Qubit_Reduction(QubitHamiltonian,
                             Hamilt.molecule.n_electrons,
                             Hamilt.molecule.n_qubits)

In [6]:
indices_to_KEEP = [2,3,4,5,6,7]

NEW_Sec_Quant_CC_ops_ia, NEW_Sec_Quant_CC_ops_ijab, theta_ia, theta_ijab = ansatz_obj.Reduced_ia_ijab_terms(
                                         Hamilt.molecule.n_qubits, 
                                         Hamilt.molecule.n_electrons, 
                                         indices_to_KEEP)
NEW_Sec_Quant_CC_ops_ia

[-1.0 [2^ 4] +
 1.0 [4^ 2],
 -1.0 [2^ 6] +
 1.0 [6^ 2],
 -1.0 [3^ 5] +
 1.0 [5^ 3],
 -1.0 [3^ 7] +
 1.0 [7^ 3]]

In [7]:
NEW_Sec_Quant_CC_ops_ijab

[-1.0 [2^ 3^ 4 5] +
 1.0 [5^ 4^ 3 2],
 -1.0 [2^ 3^ 4 7] +
 1.0 [7^ 4^ 3 2],
 -1.0 [2^ 3^ 6 7] +
 1.0 [7^ 6^ 3 2]]

In [8]:
# REDUCTION
Qubit_Op_list_Second_Quant_CC_Ops_ia, Qubit_Op_list_Second_Quant_CC_Ops_ijab = ansatz_obj.UCCSD_single_trotter_step(
                        NEW_Sec_Quant_CC_ops_ia,
                        NEW_Sec_Quant_CC_ops_ijab,
                        transformation='BK')
# Qubit_Op_list_Second_Quant_CC_Ops_ijab

In [9]:
print('finding DOUBLE e- operators only acted on by I or Z')
print('')
print(Qubit_Op_list_Second_Quant_CC_Ops_ijab)

indices_to_Remove_ijab = ansatz_obj.Find_Qubits_only_acted_on_by_I_or_Z(Qubit_Op_list_Second_Quant_CC_Ops_ijab)
print('')
print('qubit indices:', indices_to_Remove_ijab, 'only acted on by I or Z')

finding DOUBLE e- operators only acted on by I or Z

[0.125j [Z1 X2 Z3 Y4] +
0.125j [Z1 X2 Z3 Y4 Z5] +
-0.125j [Z1 Y2 Z3 X4] +
-0.125j [Z1 Y2 Z3 X4 Z5] +
0.125j [X2 Y4] +
0.125j [X2 Y4 Z5] +
-0.125j [Y2 X4] +
-0.125j [Y2 X4 Z5], 0.125j [Z1 X2 Z3 X4 Y5 Z6] +
0.125j [Z1 X2 Y4 X5 Z7] +
0.125j [Z1 Y2 Z3 Y4 Y5 Z6] +
-0.125j [Z1 Y2 X4 X5 Z7] +
0.125j [X2 Z3 Y4 X5 Z7] +
0.125j [X2 X4 Y5 Z6] +
-0.125j [Y2 Z3 X4 X5 Z7] +
0.125j [Y2 Y4 Y5 Z6], 0.125j [Z1 X2 Z3 Y6] +
0.125j [Z1 X2 Z5 Y6 Z7] +
-0.125j [Z1 Y2 Z3 X6] +
-0.125j [Z1 Y2 Z5 X6 Z7] +
0.125j [X2 Z3 Z5 Y6 Z7] +
0.125j [X2 Y6] +
-0.125j [Y2 Z3 Z5 X6 Z7] +
-0.125j [Y2 X6]]

qubit indices: [ 0  1  3  7  8  9 10 11] only acted on by I or Z


In [10]:
print('finding SINGLE e- operators only acted on by I or Z')
print('')
print(Qubit_Op_list_Second_Quant_CC_Ops_ia)

indices_to_Remove_ia = ansatz_obj.Find_Qubits_only_acted_on_by_I_or_Z(Qubit_Op_list_Second_Quant_CC_Ops_ia)
print('')
print('qubit indices:', indices_to_Remove_ia, 'only acted on by I or Z')

finding SINGLE e- operators only acted on by I or Z

[0.5j [Z1 X2 Y3 X4] +
0.5j [Z1 Y2 Y3 Y4], 0.5j [Z1 X2 Y3 Z5 X6] +
0.5j [Z1 Y2 Y3 Z5 Y6], 0.5j [Z1 Z2 Y3 Z4 X5] +
-0.5j [X3 Y5], 0.5j [Z1 Z2 Y3 Z5 Z6] +
-0.5j [Y3 Z7]]

qubit indices: [ 0  1  7  8  9 10 11] only acted on by I or Z


#### find overlap of allowed indices to remove

In [11]:
indices_to_Remove = list(set(indices_to_Remove_ijab).intersection(indices_to_Remove_ia))
indices_to_Remove

[0, 1, 7, 8, 9, 10, 11]

In [12]:
# only Z terms in H remain!!!!!
from openfermion import qubit_operator_sparse
from openfermion.ops import QubitOperator

MAT = qubit_operator_sparse(QubitOperator('Z0 X1', 1))

zero = np.array([[1],[0]])
one = np.array([[0],[1]])

state = reduce(np.kron, [one, zero])

state.conj().transpose().dot(MAT.todense().dot(state))

matrix([[0.+0.j]])

### Can remove these terms from Hamiltonian

In [13]:
reduced_Qubit_Hamiltonian = ansatz_obj.Remove_indices_from_Hamiltonian(indices_to_Remove)
reduced_Qubit_Hamiltonian

(-7.276869512497721+0j) [] +
(0.009344683608051955+0j) [X2 X3 X4 X5] +
(-0.0002763469689735821+0j) [X2 X3 Y4 Y5 Z6] +
(0.004836443728006919+0j) [X2 X3 Z4 Y5 Y6] +
(0.0003218455426212461+0j) [X2 Y3 X4 Y5] +
(0.004739070747211217+0j) [X2 Y3 Y4 X5] +
(0.004560096759033337+0j) [X2 Y3 Y4 X5 Z6] +
(-0.004836443728006919+0j) [X2 Y3 Y5 X6] +
(0.0022366866582395595+0j) [X2 Z3 X4] +
(0.006727778833177147+0j) [X2 Z3 Z5 X6] +
(0.006727778833177147+0j) [X2 Z3 X6] +
(0.0022366866582395595+0j) [X2 X4 Z5] +
(0.0002763469689735821+0j) [Y2 X3 X4 Y5 Z6] +
(0.009344683608051955+0j) [Y2 X3 Y4 X5] +
(-0.004836443728006919+0j) [Y2 X3 Z4 Y5 X6] +
(-0.004739070747211217+0j) [Y2 Y3 X4 X5] +
(-0.004560096759033337+0j) [Y2 Y3 X4 X5 Z6] +
(0.0003218455426212461+0j) [Y2 Y3 Y4 Y5] +
(-0.004836443728006919+0j) [Y2 Y3 Y5 Y6] +
(0.0022366866582395595+0j) [Y2 Z3 Y4] +
(0.006727778833177147+0j) [Y2 Z3 Z5 Y6] +
(0.006727778833177147+0j) [Y2 Z3 Y6] +
(0.0022366866582395595+0j) [Y2 Y4 Z5] +
(0.026230489264678608+0j) [Z2] +


### Can remove these terms from Anstz

In [14]:
reduced_ijab_CC = ansatz_obj.Remove_indices_from_CC_qubit_operators(Qubit_Op_list_Second_Quant_CC_Ops_ijab,
                                                             indices_to_Remove)
reduced_ijab_CC

[0.125j [X2 Z3 Y4] +
 0.125j [X2 Z3 Y4 Z5] +
 0.125j [X2 Y4] +
 0.125j [X2 Y4 Z5] +
 -0.125j [Y2 Z3 X4] +
 -0.125j [Y2 Z3 X4 Z5] +
 -0.125j [Y2 X4] +
 -0.125j [Y2 X4 Z5],
 0.125j [X2 Z3 X4 Y5 Z6] +
 0.125j [X2 Z3 Y4 X5] +
 0.125j [X2 X4 Y5 Z6] +
 0.125j [X2 Y4 X5] +
 -0.125j [Y2 Z3 X4 X5] +
 0.125j [Y2 Z3 Y4 Y5 Z6] +
 -0.125j [Y2 X4 X5] +
 0.125j [Y2 Y4 Y5 Z6],
 0.125j [X2 Z3 Z5 Y6] +
 0.125j [X2 Z3 Y6] +
 0.125j [X2 Z5 Y6] +
 0.125j [X2 Y6] +
 -0.125j [Y2 Z3 Z5 X6] +
 -0.125j [Y2 Z3 X6] +
 -0.125j [Y2 Z5 X6] +
 -0.125j [Y2 X6]]

In [15]:
reduced_ia_CC = ansatz_obj.Remove_indices_from_CC_qubit_operators(Qubit_Op_list_Second_Quant_CC_Ops_ia,
                                                             indices_to_Remove)
reduced_ia_CC

[0.5j [X2 Y3 X4] +
 0.5j [Y2 Y3 Y4],
 0.5j [X2 Y3 Z5 X6] +
 0.5j [Y2 Y3 Z5 Y6],
 0.5j [Z2 Y3 Z4 X5] +
 -0.5j [X3 Y5],
 0.5j [Z2 Y3 Z5 Z6] +
 -0.5j [Y3]]

# NEXT need to re-label everything

In [16]:
# Relabelling H
relabel_dict, relabelled_reduced_Qubit_Hamiltonian = ansatz_obj.Re_label_Hamiltonian(reduced_Qubit_Hamiltonian)

print('qubit relabelling dict = ', relabel_dict)

relabelled_reduced_Qubit_Hamiltonian

qubit relabelling dict =  {2: 0, 3: 1, 4: 2, 5: 3, 6: 4}


(-7.276869512497721+0j) [] +
(0.009344683608051955+0j) [X0 X1 X2 X3] +
(-0.0002763469689735821+0j) [X0 X1 Y2 Y3 Z4] +
(0.004836443728006919+0j) [X0 X1 Z2 Y3 Y4] +
(0.0003218455426212461+0j) [X0 Y1 X2 Y3] +
(0.004739070747211217+0j) [X0 Y1 Y2 X3] +
(0.004560096759033337+0j) [X0 Y1 Y2 X3 Z4] +
(-0.004836443728006919+0j) [X0 Y1 Y3 X4] +
(0.0022366866582395595+0j) [X0 Z1 X2] +
(0.006727778833177147+0j) [X0 Z1 Z3 X4] +
(0.006727778833177147+0j) [X0 Z1 X4] +
(0.0022366866582395595+0j) [X0 X2 Z3] +
(0.0002763469689735821+0j) [Y0 X1 X2 Y3 Z4] +
(0.009344683608051955+0j) [Y0 X1 Y2 X3] +
(-0.004836443728006919+0j) [Y0 X1 Z2 Y3 X4] +
(-0.004739070747211217+0j) [Y0 Y1 X2 X3] +
(-0.004560096759033337+0j) [Y0 Y1 X2 X3 Z4] +
(0.0003218455426212461+0j) [Y0 Y1 Y2 Y3] +
(-0.004836443728006919+0j) [Y0 Y1 Y3 Y4] +
(0.0022366866582395595+0j) [Y0 Z1 Y2] +
(0.006727778833177147+0j) [Y0 Z1 Z3 Y4] +
(0.006727778833177147+0j) [Y0 Z1 Y4] +
(0.0022366866582395595+0j) [Y0 Y2 Z3] +
(0.026230489264678608+0j) [Z0] +


In [17]:
# Relabelling ANSATZ
relabelled_reduced_ia_CC = ansatz_obj.Re_label_CC_qubit_operators(relabel_dict, reduced_ia_CC)
relabelled_reduced_ijab_CC = ansatz_obj.Re_label_CC_qubit_operators(relabel_dict, reduced_ijab_CC)
relabelled_reduced_ijab_CC

[0.125j [X0 Z1 Y2] +
 0.125j [X0 Z1 Y2 Z3] +
 0.125j [X0 Y2] +
 0.125j [X0 Y2 Z3] +
 -0.125j [Y0 Z1 X2] +
 -0.125j [Y0 Z1 X2 Z3] +
 -0.125j [Y0 X2] +
 -0.125j [Y0 X2 Z3],
 0.125j [X0 Z1 X2 Y3 Z4] +
 0.125j [X0 Z1 Y2 X3] +
 0.125j [X0 X2 Y3 Z4] +
 0.125j [X0 Y2 X3] +
 -0.125j [Y0 Z1 X2 X3] +
 0.125j [Y0 Z1 Y2 Y3 Z4] +
 -0.125j [Y0 X2 X3] +
 0.125j [Y0 Y2 Y3 Z4],
 0.125j [X0 Z1 Z3 Y4] +
 0.125j [X0 Z1 Y4] +
 0.125j [X0 Z3 Y4] +
 0.125j [X0 Y4] +
 -0.125j [Y0 Z1 Z3 X4] +
 -0.125j [Y0 Z1 X4] +
 -0.125j [Y0 Z3 X4] +
 -0.125j [Y0 X4]]

## Find New input state

In [18]:
print('old input = ', ansatz_obj.Get_BK_HF_state_in_OCC_basis())
print('BUT following indices removed:', indices_to_Remove)
ansatz_obj.New_BK_HF_state(indices_to_Remove)

old input =  [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
BUT following indices removed: [0, 1, 7, 8, 9, 10, 11]


array([1., 0., 0., 0., 0.])

# Find what new FCI energy is

In [19]:
new_Molecular_H_MATRIX = Hamilt.Get_sparse_Qubit_Hamiltonian_matrix(relabelled_reduced_Qubit_Hamiltonian)


from scipy.linalg import eig
eig_values, eig_vectors = eig(new_Molecular_H_MATRIX.todense())
new_FCI_Energy = min(eig_values)


print('new_FCI = ', new_FCI_Energy, 'VS old FCI:', Hamilt.molecule.fci_energy)

new_FCI =  (-7.859689794578902+0j) VS old FCI: -7.8756525649279085


# Look at Amplitudes

In [20]:
Hamiltonian_graph_obj = Openfermion_Hamiltonian_Graph(relabelled_reduced_Qubit_Hamiltonian)

commutativity_flag = 'AC' ## <- defines relationship between sets!!!
plot_graph = False
Graph_colouring_strategy='largest_first'
anti_commuting_sets = Hamiltonian_graph_obj.Get_Clique_Cover_as_QubitOp(commutativity_flag, Graph_colouring_strategy=Graph_colouring_strategy, plot_graph=plot_graph)
anti_commuting_sets

Building Graph Edges: 100%|##########| 62/62 [00:00<00:00, 405.33it/s]


{0: [(-7.276869512497721+0j) []],
 1: [(0.07828114149315563+0j) [Z1 Z3]],
 2: [(-0.1443201912269891+0j) [Z4],
  (0.010595797757053287+0j) [Z1 Y2 Z3 Y4],
  (-0.004836443728006919+0j) [X0 Y1 Y3 X4],
  (-0.004836443728006919+0j) [Z0 X1 X2 Y3 Y4],
  (0.006727778833177147+0j) [X0 Z1 X4]],
 3: [(0.05937749358221963+0j) [Z0 Z1 Z2 Z3],
  (0.006727778833177147+0j) [X0 Z1 Z3 X4],
  (0.004836443728006919+0j) [Z0 X1 Y2 Y3 X4],
  (0.004836443728006919+0j) [X0 X1 Z2 Y3 Y4]],
 4: [(0.05937749358221963+0j) [Z0 Z2],
  (0.010595797757053287+0j) [Z1 X2 Z3 X4],
  (0.006727778833177147+0j) [Y0 Z1 Z3 Y4],
  (-0.004836443728006919+0j) [Y0 X1 Z2 Y3 X4]],
 5: [(-0.14432019122698903+0j) [Z1 Z3 Z4],
  (-0.004836443728006919+0j) [X1 Y2 X3 Y4],
  (0.010595797757053287+0j) [X2 Z3 X4],
  (0.006727778833177147+0j) [Y0 Z1 Y4]],
 6: [(0.004739070747211217+0j) [X0 Y1 Y2 X3],
  (0.07521726040101417+0j) [Z0 Z1 Z3 Z4],
  (0.010595797757053287+0j) [Y2 Z3 Y4]],
 7: [(-0.004739070747211217+0j) [Y0 Y1 X2 X3],
  (0.026230489264

In [36]:
longest = max(len(item) for item in anti_commuting_sets.values())
max_key, max_value = max(anti_commuting_sets.items(), key = lambda x: len(x[1]))
print('longest set =', longest)
print('set key for this =', max_key)

np.log2(5)

longest set = 5
set key for this = 2


2.321928094887362

In [21]:
from quchem.LCU_method import *

In [22]:
check_LCU_reduction=False
N_index=0

ancilla_amps={}
l1_norms={}

for key in anti_commuting_sets:
    if len(anti_commuting_sets[key])>1:
        R_uncorrected, Pn, gamma_l = Get_R_op_list(anti_commuting_sets[key], N_index,
                                                               check_operator=check_LCU_reduction)
        R_corrected_Op_list, R_corr_list, ancilla_amplitudes, l1_norm = absorb_complex_phases(R_uncorrected)
        ancilla_amps[key]=ancilla_amplitudes
        l1_norms[key]=l1_norm
    else:
        continue

In [23]:
l1_norms

{2: 1.9357070483028453,
 3: 1.1335693763422579,
 4: 1.1769295742243522,
 5: 1.6921536212310313,
 6: 1.5023482132220016,
 7: 1.535025478495078,
 8: 1.4614993530682343,
 9: 1.4132034886598075,
 10: 1.4142108695115105,
 11: 1.0018352951670078,
 12: 1.085261210371627,
 13: 1.4132034886598075,
 14: 1.0010281795360543,
 15: 1.0339386283389613,
 16: 1.414210684432645,
 17: 1.414009967937555,
 18: 1.1103057228836954,
 19: 1.4142125126091394,
 20: 1.404467766465558,
 21: 1.0531324123974257,
 22: 1.1103057228836954,
 23: 1.4106045930890132,
 24: 1.4142087390038238,
 25: 1.4142087390038238}

In [24]:
print(min(l1_norms.values()))

print('Highest probability of success = {}'.format((1/min(l1_norms.values()))**2))

print('No of repeats = {}'.format(min(l1_norms.values())**2))

1.0010281795360543
Highest probability of success = 0.9979468080451747
No of repeats = 1.002057416225267


In [25]:
print(max(l1_norms.values()))

print('Lowest probability of success = {}'.format((1/max(l1_norms.values()))**2))

print('No of repeats = {}'.format(max(l1_norms.values())**2))

1.9357070483028453
Lowest probability of success = 0.26688289327596615
No of repeats = 3.746961776849314


In [26]:
ancilla_amps

{2: [0.1596548719153918,
  0.6184528703952749,
  0.4178331076027831,
  0.4178331076027831,
  0.49280559793444656],
 3: [0.9377318313647549,
  0.2224769337620467,
  0.18863062634304711,
  0.18863062634304711],
 4: [0.9189141133992293,
  0.27276092613734315,
  0.21734576348939164,
  0.18428008156504788],
 5: [0.16568063058262109,
  0.4607166902504476,
  0.6819267174856639,
  0.5433838532323587],
 6: [0.696491350576119, 0.671805301802822, 0.25214566235069924],
 7: [0.6468546021008121, 0.7007424217083301, 0.3008972950349421],
 8: [0.6841446513144441, 0.705644043400044, 0.18442499855462816],
 9: [0.6936082352206344, 0.7203524248825133],
 10: [0.7064164902422666, 0.7077963989127082],
 11: [0.9990827707493171, 0.04282075655412605],
 12: [0.9579977848267611, 0.28677559914856565],
 13: [0.6936082352206344, 0.7203524248825133],
 14: [0.03205701243317465, 0.9994860419004656],
 15: [0.9831573923650422, 0.18276088705729776],
 16: [0.7078196919890571, 0.706393150895814],
 17: [0.7130814171896465, 0.

In [27]:
from quchem.latex_tables import *

In [28]:
latex_table_Hamiltonian(anti_commuting_sets, 'Latex_table1')
latex_table_seq_rot(anti_commuting_sets, 'Latex_table2', 0)
latex_table_LCU(anti_commuting_sets, 'Latex_table3', 0)
latex_table_LCU_R_op(anti_commuting_sets, 'Latex_table4', 0)

\begin{tabular}{rl}
\toprule
 l index &                                                                                                                                                                                            \$H\_\{S\_\{l\}\}\$ \\
\midrule
       0 &                                                                                                                                                                           [(-7.276869512497721+0j) []] \\
       1 &                                                                                                                                                                     [(0.07828114149315563+0j) [Z1 Z3]] \\
       2 &  [(-0.1443201912269891+0j) [Z4], (0.010595797757053287+0j) [Z1 Y2 Z3 Y4], (-0.004836443728006919+0j) [X0 Y1 Y3 X4], (-0.004836443728006919+0j) [Z0 X1 X2 Y3 Y4], (0.006727778833177147+0j) [X0 Z1 X4]] \\
       3 &                              [(0.05937749358221963+0j) [Z0 Z1 Z2 Z3], (0.006727778833177147