# Hamiltonian class

In [1]:
from openfermion.chem import MolecularData

In [2]:
from quchem.Hamiltonian.Hamiltonian_Generator_Functions import *

In [3]:
### Variable Parameters
Molecule = 'H2'
geometry = [('H', (0., 0., 0.)), ('H', (0., 0., 0.74))]

# Molecule = 'LiH'
# geometry = [('Li', (0., 0., 0.)), ('H', (0., 0., 1.45))]

In [4]:
### initialise Hamiltonian class
Hamilt = Hamiltonian_PySCF(Molecule,
                     run_scf=1, run_mp2=1, run_cisd=1, run_ccsd=1, run_fci=1,
                     basis='sto-3g',
                     multiplicity=1,
                     geometry=geometry)  # normally None!

## get molecule's geometry if not defined

In [5]:
Hamilt.Get_Geometry()
Hamilt.geometry

[('H', (2, 0, 0)), ('H', (3, 0, 0))]

## Run PySCF calculation

In [6]:
Hamilt.Run_PySCF()
Hamilt.PrintInfo()

Geometry:  [('H', (2, 0, 0)), ('H', (3, 0, 0))]
No Qubits:  4
No. Spin Orbitals:  4
multiplicity:  1
HF Energy:  -1.066108649317937
CCSD:  -1.1011503302444794
FCI:  -1.101150330232619


## Get molecular Hamiltonian
- note if no PySCF calculation done it will perform this first

also: gives singles Hamiltonian and doubles Hamiltonian

$$H = constant +\sum_{p, q} h_{p, q} a_{p}^{\dagger} a_{q}+\sum_{p, q, r, s} h_{p, q, r, s} a_{p}^{\dagger} a_{q}^{\dagger} a_{r} a_{s}$$

In [7]:
#give second quant molecular Hamiltonian:
Hamilt.Get_Molecular_Hamiltonian(Get_H_matrix=True)
print(Hamilt.MolecularHamiltonian)

#if Get_H_matrix=True ... then the matrix of this Hamiltonian is found
Hamilt.MolecularHamiltonianMatrix.todense()

() 0.52917721092
((0, 1), (0, 0)) -1.1108441798837276
((1, 1), (1, 0)) -1.1108441798837276
((2, 1), (2, 0)) -0.589121003706083
((3, 1), (3, 0)) -0.589121003706083
((0, 1), (0, 1), (0, 0), (0, 0)) 0.31320124976475916
((0, 1), (0, 1), (2, 0), (2, 0)) 0.09839529174273517
((0, 1), (1, 1), (1, 0), (0, 0)) 0.31320124976475916
((0, 1), (1, 1), (3, 0), (2, 0)) 0.09839529174273517
((0, 1), (2, 1), (0, 0), (2, 0)) 0.09839529174273517
((0, 1), (2, 1), (2, 0), (0, 0)) 0.31085338155985687
((0, 1), (3, 1), (1, 0), (2, 0)) 0.09839529174273517
((0, 1), (3, 1), (3, 0), (0, 0)) 0.31085338155985687
((1, 1), (0, 1), (0, 0), (1, 0)) 0.31320124976475916
((1, 1), (0, 1), (2, 0), (3, 0)) 0.09839529174273517
((1, 1), (1, 1), (1, 0), (1, 0)) 0.31320124976475916
((1, 1), (1, 1), (3, 0), (3, 0)) 0.09839529174273517
((1, 1), (2, 1), (0, 0), (3, 0)) 0.09839529174273517
((1, 1), (2, 1), (2, 0), (1, 0)) 0.31085338155985687
((1, 1), (3, 1), (1, 0), (3, 0)) 0.09839529174273517
((1, 1), (3, 1), (3, 0), (1, 0)) 0.3108533

matrix([[ 0.52917721+0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j],
        [ 0.        +0.j, -0.05994379+0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j],
        [ 0.        +0.j,  0.        +0.j, -0.05994379+0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j],
        [ 0.       

Can get singles Hamiltonian: $h_{p, q}$ terms:

In [8]:
print(Hamilt.singles_hamiltonian)

[[-1.11084418  0.          0.          0.        ]
 [ 0.         -1.11084418  0.          0.        ]
 [ 0.          0.         -0.589121    0.        ]
 [ 0.          0.          0.         -0.589121  ]]


Can get singles Hamiltonian: $ h_{p, q, r, s}$ terms:

In [9]:
print(Hamilt.doubles_hamiltonian)

[[[[0.31320125 0.         0.         0.        ]
   [0.         0.         0.         0.        ]
   [0.         0.         0.09839529 0.        ]
   [0.         0.         0.         0.        ]]

  [[0.         0.         0.         0.        ]
   [0.31320125 0.         0.         0.        ]
   [0.         0.         0.         0.        ]
   [0.         0.         0.09839529 0.        ]]

  [[0.         0.         0.09839529 0.        ]
   [0.         0.         0.         0.        ]
   [0.31085338 0.         0.         0.        ]
   [0.         0.         0.         0.        ]]

  [[0.         0.         0.         0.        ]
   [0.         0.         0.09839529 0.        ]
   [0.         0.         0.         0.        ]
   [0.31085338 0.         0.         0.        ]]]


 [[[0.         0.31320125 0.         0.        ]
   [0.         0.         0.         0.        ]
   [0.         0.         0.         0.09839529]
   [0.         0.         0.         0.        ]]

  [[0.  

## Find CCSD amplitudes from CLASSICAL quantum chem calculation

Coupled cluster considers **single** and **double** electron excitations from HF state.

$$U_{CCSD} =e^{\left(T_{1}-T_{1}^{\dagger}\right)+\left(T_{2}-T_{2}^{\dagger}\right)}$$

$$T_{1} = \sum_{\substack{i\in occ \\  \alpha \in virt}} t_{\alpha}^{i}a_{\alpha}^{\dagger}a_{i}$$


$$T_{2} = \sum_{\substack{i>j\in occ, \\  \alpha > \beta \in virt}} t_{\alpha \beta}^{ij}a_{\alpha}^{\dagger}a_{\beta}^{\dagger}a_{i}a_{j}$$

Overall:

$$|\psi_{UCC}\rangle = e^{T-T^{\dagger}}|\psi_{HF}\rangle$$

^^ looking at classical calculation... we can find the **most important terms!**

In [10]:
Hamilt.Get_CCSD_Amplitudes()

# indexing is a,i (un_occupied=a and occupied=i)
print(Hamilt.molecule.single_cc_amplitudes)

# indexing is a,i, b, j (occupied=i,j and un_occupied=a,b)
print(Hamilt.molecule.double_cc_amplitudes)

print(np.where(Hamilt.molecule.double_cc_amplitudes!=0))
# for H2 == e- excited from 0-->2 and 1-->3
Hamilt.molecule.double_cc_amplitudes[2,0,3,1]


[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.44369174e-17 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.44369174e-17 0.00000000e+00 0.00000000e+00]]
[[[[ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]]

  [[ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]]

  [[ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]]

  [[ 0.          0.          0.          0.        ]
   [ 0.          0.          0.          0.        ]

-0.08903292095053292

## Get natural orbital occupation number (NOON)

Takes 1-RDM (in the canonical orbital basis from a CISD calculation) which are arranged as "spin-up, spin-down, spin-up, spin-down..." combining the spin up and down terms. Diagnoalizing the resultant matrix gives the 1-RDM fermionic natural molecular orbitals (NMO) basis. Eigenvalues of this matrix are the natural orbital occupation number (NOON). Orbitals with a small NOON can be assumed to be UNFILLED and REMOVED from the Hamiltonian! Orbitals with large NOON (close to 2) can assumed to be FILLED and also removed!


In [11]:
transformation='JW'

NOON, NMO_basis, new_ROTATED_Qubit_Hamiltonian = Hamilt.Get_NOON(transformation)
print(NOON)

print(new_ROTATED_Qubit_Hamiltonian)

[1.93853404 0.06146596]
(-0.32760818967480887+0j) [] +
(-0.049197645871367594+0j) [X0 X1 Y2 Y3] +
(0.049197645871367594+0j) [X0 Y1 Y2 X3] +
(0.049197645871367594+0j) [Y0 X1 X2 Y3] +
(-0.049197645871367594+0j) [Y0 Y1 X2 X3] +
(0.13716572937099492+0j) [Z0] +
(0.15660062488237958+0j) [Z0 Z1] +
(0.10622904490856086+0j) [Z0 Z2] +
(0.15542669077992843+0j) [Z0 Z3] +
(0.13716572937099492+0j) [Z1] +
(0.15542669077992843+0j) [Z1 Z2] +
(0.10622904490856086+0j) [Z1 Z3] +
(-0.1303629205710914+0j) [Z2] +
(0.16326768673564357+0j) [Z2 Z3] +
(-0.13036292057109136+0j) [Z3]


## Get Fermionic Molecular Hamiltonian

$$H = constant +\sum_{p, q} h_{p, q} a_{p}^{\dagger} a_{q}+\sum_{p, q, r, s} h_{p, q, r, s} a_{p}^{\dagger} a_{q}^{\dagger} a_{r} a_{s}$$

In [12]:
Hamilt.Get_Fermionic_Hamiltonian()

0.52917721092 [] +
-1.1108441798837276 [0^ 0] +
0.31320124976475916 [0^ 0^ 0 0] +
0.09839529174273517 [0^ 0^ 2 2] +
0.31320124976475916 [0^ 1^ 1 0] +
0.09839529174273517 [0^ 1^ 3 2] +
0.09839529174273517 [0^ 2^ 0 2] +
0.31085338155985687 [0^ 2^ 2 0] +
0.09839529174273517 [0^ 3^ 1 2] +
0.31085338155985687 [0^ 3^ 3 0] +
0.31320124976475916 [1^ 0^ 0 1] +
0.09839529174273517 [1^ 0^ 2 3] +
-1.1108441798837276 [1^ 1] +
0.31320124976475916 [1^ 1^ 1 1] +
0.09839529174273517 [1^ 1^ 3 3] +
0.09839529174273517 [1^ 2^ 0 3] +
0.31085338155985687 [1^ 2^ 2 1] +
0.09839529174273517 [1^ 3^ 1 3] +
0.31085338155985687 [1^ 3^ 3 1] +
0.3108533815598569 [2^ 0^ 0 2] +
0.09839529174273517 [2^ 0^ 2 0] +
0.3108533815598569 [2^ 1^ 1 2] +
0.09839529174273517 [2^ 1^ 3 0] +
-0.589121003706083 [2^ 2] +
0.09839529174273517 [2^ 2^ 0 0] +
0.32653537347128714 [2^ 2^ 2 2] +
0.09839529174273517 [2^ 3^ 1 0] +
0.32653537347128714 [2^ 3^ 3 2] +
0.3108533815598569 [3^ 0^ 0 3] +
0.09839529174273517 [3^ 0^ 2 1] +
0.310853381559

## Get Qubit Hamiltonian

$$H = \sum_{i} \alpha_{i} P_{i}$$

#### Jordan Wigner Transformation:

In [13]:
Hamilt.Get_Qubit_Hamiltonian(threshold=None, transformation='JW')

(-0.32760818967480887+0j) [] +
(-0.049197645871367594+0j) [X0 X1 Y2 Y3] +
(0.049197645871367594+0j) [X0 Y1 Y2 X3] +
(0.049197645871367594+0j) [Y0 X1 X2 Y3] +
(-0.049197645871367594+0j) [Y0 Y1 X2 X3] +
(0.13716572937099492+0j) [Z0] +
(0.15660062488237958+0j) [Z0 Z1] +
(0.10622904490856086+0j) [Z0 Z2] +
(0.15542669077992843+0j) [Z0 Z3] +
(0.13716572937099492+0j) [Z1] +
(0.15542669077992843+0j) [Z1 Z2] +
(0.10622904490856086+0j) [Z1 Z3] +
(-0.1303629205710914+0j) [Z2] +
(0.16326768673564357+0j) [Z2 Z3] +
(-0.13036292057109136+0j) [Z3]

In [14]:
#Threshold can be used to remove small terms
Hamilt.Get_Qubit_Hamiltonian(threshold=0.14, transformation='JW')

(-0.32760818967480887+0j) [] +
(0.15660062488237958+0j) [Z0 Z1] +
(0.15542669077992843+0j) [Z0 Z3] +
(0.15542669077992843+0j) [Z1 Z2] +
(0.16326768673564357+0j) [Z2 Z3]

#### Bravyi kitaev transformation:

In [15]:
Hamilt.Get_Qubit_Hamiltonian(threshold=None, transformation='BK')

(-0.32760818967480887+0j) [] +
(0.049197645871367594+0j) [X0 Z1 X2] +
(0.049197645871367594+0j) [X0 Z1 X2 Z3] +
(0.049197645871367594+0j) [Y0 Z1 Y2] +
(0.049197645871367594+0j) [Y0 Z1 Y2 Z3] +
(0.13716572937099492+0j) [Z0] +
(0.13716572937099492+0j) [Z0 Z1] +
(0.15542669077992843+0j) [Z0 Z1 Z2] +
(0.15542669077992843+0j) [Z0 Z1 Z2 Z3] +
(0.10622904490856086+0j) [Z0 Z2] +
(0.10622904490856086+0j) [Z0 Z2 Z3] +
(0.15660062488237958+0j) [Z1] +
(-0.13036292057109136+0j) [Z1 Z2 Z3] +
(0.16326768673564357+0j) [Z1 Z3] +
(-0.1303629205710914+0j) [Z2]

## Convert QubitOperator to matrix

In [16]:
Qubit_Op = Hamilt.Get_Qubit_Hamiltonian(threshold=None, transformation='BK')

matrix_qubit_op = Hamilt.Get_sparse_Qubit_Hamiltonian_matrix(Qubit_Op)
matrix_qubit_op.todense()

matrix([[ 0.52917721+0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j],
        [ 0.        +0.j, -0.05994379+0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j],
        [ 0.        +0.j,  0.        +0.j,  0.00400595+0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.19679058+0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j],
        [ 0.       