In [1]:
import os
import ast
import cirq
import numpy as np

In [2]:
### open Hamiltonian data ###

working_dir = os.getcwd()
parent_dir = os.path.dirname(working_dir) # gets directory where running python file is!

data_dir = os.path.join(parent_dir, 'Molecular_Hamiltonian_data')
hamiltonian_data = os.path.join(data_dir, 'hamiltonians.txt')

In [3]:
with open(hamiltonian_data, 'r') as input_file:
    hamiltonians = ast.literal_eval(input_file.read())

for key in hamiltonians.keys():
    print(f"{key: <25}     n_qubits:  {hamiltonians[key][1]:<5.0f}")

H2-S1_STO-3G_singlet          n_qubits:  18   
C1-O1_STO-3G_singlet          n_qubits:  16   
H1-Cl1_STO-3G_singlet         n_qubits:  16   
H1-Na1_STO-3G_singlet         n_qubits:  16   
H2-Mg1_STO-3G_singlet         n_qubits:  17   
H1-F1_3-21G_singlet           n_qubits:  18   
H1-Li1_3-21G_singlet          n_qubits:  18   
Be1_STO-3G_singlet            n_qubits:  5    
H1-F1_STO-3G_singlet          n_qubits:  8    
H1-Li1_STO-3G_singlet         n_qubits:  8    
Ar1_STO-3G_singlet            n_qubits:  13   
F2_STO-3G_singlet             n_qubits:  15   
H1-O1_STO-3G_singlet          n_qubits:  8    
H2-Be1_STO-3G_singlet         n_qubits:  9    
H2-O1_STO-3G_singlet          n_qubits:  10   
H2_3-21G_singlet              n_qubits:  5    
H2_6-31G_singlet              n_qubits:  5    
H3-N1_STO-3G_singlet          n_qubits:  13   
H4-C1_STO-3G_singlet          n_qubits:  14   
Mg1_STO-3G_singlet            n_qubits:  13   
N2_STO-3G_singlet             n_qubits:  15   
Ne1_STO-3G_si

In [4]:
molecule_key = 'H3_STO-3G_singlet_1+'
transformation, N_qubits, Hamilt_dictionary, _ ,_, _ = hamiltonians[molecule_key]

# 1. Get OpenFermion representation of Hamiltonian

In [5]:
from quchem.Misc_functions.conversion_scripts import Get_Openfermion_Hamiltonian

openFermion_H = Get_Openfermion_Hamiltonian(Hamilt_dictionary)
openFermion_H

-1.7512307459285525 [] +
0.01872992170537467 [X0] +
-0.023568139980123585 [X0 X1] +
0.03597868636603963 [X0 X1 X2] +
-0.023568139980123585 [X0 X1 Z2] +
-0.03597868636603963 [X0 Y1 Y2] +
0.01872992170537467 [X0 Z1] +
0.023568139980123585 [X0 Z1 X2] +
0.01872992170537467 [X0 Z1 Z2] +
0.023568139980123585 [X0 X2] +
0.01872992170537467 [X0 Z2] +
0.03597868636603963 [Y0 X1 Y2] +
-0.023568139980123585 [Y0 Y1] +
0.03597868636603963 [Y0 Y1 X2] +
-0.023568139980123585 [Y0 Y1 Z2] +
0.023568139980123585 [Y0 Z1 Y2] +
0.023568139980123585 [Y0 Y2] +
-0.45436486525596403 [Z0] +
0.02356815233618002 [Z0 X1] +
0.02356815233617983 [Z0 X1 Z2] +
-0.07195737217001562 [Z0 Y1 Y2] +
0.37110605476609804 [Z0 Z1] +
-0.023568152336179825 [Z0 Z1 X2] +
-0.2878474382772282 [Z0 Z1 Z2] +
-0.023568152336180023 [Z0 X2] +
0.37110605476609787 [Z0 Z2] +
0.02356815233618002 [X1] +
0.02356815233617983 [X1 Z2] +
-0.07195737217001562 [Y1 Y2] +
-0.017109477140260287 [Z1] +
-0.023568152336179825 [Z1 X2] +
0.31270210682950855 [Z1 

# 2. Get cliques defined by commutativity 


In [6]:
from quchem.Unitary_Partitioning.Graph import Clique_cover_Hamiltonian

commutativity_flag = 'AC' ## <- defines relationship between sets!!!
Graph_colouring_strategy='largest_first'


anti_commuting_sets = Clique_cover_Hamiltonian(openFermion_H, 
                                                     N_qubits, 
                                                     commutativity_flag, 
                                                     Graph_colouring_strategy)
anti_commuting_sets

{0: [-1.7512307459285525 []],
 1: [-0.017109477140260287 [Z2],
  -0.023568152336179825 [Z1 X2],
  0.03597868636603963 [X0 X1 X2],
  0.023568139980123585 [Y0 Z1 Y2]],
 2: [0.02356815233617983 [X1 Z2],
  -0.017109477140260287 [Z1],
  0.03597868636603963 [Y0 X1 Y2],
  -0.023568139980123585 [Y0 Y1]],
 3: [0.37110605476609787 [Z0 Z2],
  -0.023568152336179825 [Z0 Z1 X2],
  0.01872992170537467 [X0],
  -0.023568139980123585 [Y0 Y1 Z2]],
 4: [0.02356815233617983 [Z0 X1 Z2],
  0.37110605476609804 [Z0 Z1],
  0.01872992170537467 [X0 Z2],
  0.023568139980123585 [X0 Z1 X2]],
 5: [0.023568139980123585 [X0 X2],
  -0.023568139980123585 [X0 X1 Z2],
  0.01872992170537467 [X0 Z1 Z2],
  0.03597868636603963 [Y0 Y1 X2],
  -0.45436486525596403 [Z0]],
 6: [-0.023568139980123585 [X0 X1],
  -0.03597868636603963 [X0 Y1 Y2],
  0.01872992170537467 [X0 Z1],
  0.023568139980123585 [Y0 Y2]],
 7: [-0.023568152336180023 [X2], -0.07195737217001562 [Y1 Y2]],
 8: [0.02356815233618002 [X1], 0.31270210682950855 [Z1 Z2]],
 9:

# 3. custom cirq functions

### 3.1 custom single qubit pauli with phase

In [7]:
from quchem.Unitary_Partitioning.LCU_circuit_functions import singeQ_Pauligate_phase

gate_obj = singeQ_Pauligate_phase('X', -1j)
circuit = cirq.Circuit(gate_obj.on(cirq.LineQubit(1)))
print(circuit)

print('')
print(cirq.Circuit(cirq.decompose(circuit)))

1: ───(-0-1j) X───

1: ───Y───Z───


In [8]:
## CHECKING ALL possibitlies
Pauli_dict = { 'X':np.array([[0.+0.j, 1.+0.j],
                       [1.+0.j, 0.+0.j]]),
                  'Y':np.array([[0.+0.j, 0.-1.j],
                       [0.+1.j, 0.+0.j]]), 
                  'Z':np.array([[ 1.+0.j,  0.+0.j],
                   [ 0.+0.j, -1.+0.j]]), 
                  'I':np.eye(2)}

phase_list = [1, -1, 1j, -1j]

for pstr in Pauli_dict.keys():
    for phase in phase_list:
        gate_obj = singeQ_Pauligate_phase(pstr, phase)
        circuit = cirq.Circuit(gate_obj.on(cirq.LineQubit(1)))
        print(np.allclose(circuit.unitary(), phase*Pauli_dict[pstr]))

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


### 3.2 custom PauliWord with phase

In [9]:
from openfermion.ops import QubitOperator
from quchem.Unitary_Partitioning.LCU_circuit_functions import Modified_PauliWord_gate

PauliQubitOp = QubitOperator('Y0 X1 X2 X3',1)
Pn = QubitOperator('Z2',1)
correction_val = -1j
circuit_obj = Modified_PauliWord_gate(PauliQubitOp, correction_val, Pn).on(*list(cirq.LineQubit.range(4)))
circuit=cirq.Circuit(circuit_obj)
print(circuit)

print('')
print('')
print('')
print(cirq.Circuit(cirq.decompose(circuit)))

0: ───Y0───────────
      │
1: ───X1───────────
      │
2: ───(-0-1j)*X2───
      │
3: ───X3───────────



0: ───Y───────

1: ───X───────

2: ───Y───Z───

3: ───X───────


In [10]:
from functools import reduce

## checking
Pword_mat = reduce(np.kron, [Pauli_dict['Y'], Pauli_dict['X'], -1j*Pauli_dict['X'], Pauli_dict['X']])
np.array_equal(circuit.unitary(), Pword_mat)

True

### 3.3 custom PauliWord with phase and controls

In [11]:
OP = QubitOperator('X1 Y2')
correction_val=-1j

qubit_list = cirq.LineQubit.range(3, 5) + cirq.LineQubit.range(3) 
mod_p_word_gate = Modified_PauliWord_gate(OP, correction_val, Pn).controlled(num_controls=2, control_values=[0,1]).on(*qubit_list) 
circuit_with_controls = cirq.Circuit(mod_p_word_gate)
print(circuit_with_controls)

print('')
print('')
print('')
print(cirq.Circuit(cirq.decompose(circuit_with_controls)))

0: ───I────────────
      │
1: ───X1───────────
      │
2: ───(-0-1j)*Y2───
      │
3: ───(0)──────────
      │
4: ───@────────────



1: ───X─────────────────
      │
2: ───┼─────Z─────X─────
      │     │     │
3: ───(0)───(0)───(0)───
      │     │     │
4: ───@─────@─────@─────


In [12]:
## CHECK ## 

zero = np.array([[1],[0]])
one = np.array([[0],[1]])

zero_zero = reduce(np.kron, [zero, zero])
zero_one = reduce(np.kron, [zero, one])
one_zero = reduce(np.kron, [one, zero])
one_one = reduce(np.kron, [one, one])

X=cirq.X._unitary_()
Y=cirq.Y._unitary_()
Z= cirq.Z._unitary_()
I = np.eye(2)

N_sys=3
system_I = np.eye(2**N_sys)

# (I x |00> <00|) + (IX -1jY x |01> <01|) + (I x |10> <10|) + (I x |11> <11|)  
control_op = (np.kron(system_I, np.outer(zero_zero, zero_zero)) + 
             np.kron(reduce(np.kron, [I, X, -1j*Y]), np.outer(zero_one, zero_one)) + 
             np.kron(system_I, np.outer(one_zero, one_zero)) + 
             np.kron(system_I, np.outer(one_one, one_one)))

np.array_equal(control_op, circuit_with_controls.unitary())

True

# 4. Example of R_l operator

In [45]:
key_larg, largest_AC_set = max(anti_commuting_sets.items(), key=lambda x:len(x[1])) # largest nonCon part found by dfs alg
largest_AC_set

[0.023568139980123585 [X0 X2],
 -0.023568139980123585 [X0 X1 Z2],
 0.01872992170537467 [X0 Z1 Z2],
 0.03597868636603963 [Y0 Y1 X2],
 -0.45436486525596403 [Z0]]

In [79]:
## works with:
key=6 #7
key_larg, largest_AC_set = key, anti_commuting_sets[key]
largest_AC_set

[-0.023568139980123585 [X0 X1],
 -0.03597868636603963 [X0 Y1 Y2],
 0.01872992170537467 [X0 Z1],
 0.023568139980123585 [Y0 Y2]]

In [80]:
from quchem.Unitary_Partitioning.Unitary_partitioning_LCU_method import Get_R_op_list

N_index=0
check_reduction = True

R_linear_comb_list, Pn, gamma_l = Get_R_op_list(largest_AC_set,
                                                N_index,
                                                N_qubits,
                                                check_reduction=check_reduction, 
                                                atol=1e-8,
                                                rtol=1e-05)

R_linear_comb_list

[0.5249181768963586 [],
 (-0-0.6527833916355477j) [Z1 Y2],
 (-0-0.33982846654021914j) [Y1],
 0.42761123055588435j [Z0 X1 Y2]]

To perform Unitary Partitioning via a LCU - apply the linear combination of operators in ```R_linear_comb_list```

- in Q circuit form these all must have real amplitudes
- and be l1 normalized

In [81]:
from quchem.Unitary_Partitioning.LCU_circuit_functions import absorb_complex_phases
R_linear_comb_corrected_phase_OP_list, R_linear_comb_correction_values, ancilla_amplitudes, l1_norm = absorb_complex_phases(R_linear_comb_list)

for i, op in enumerate(R_linear_comb_corrected_phase_OP_list):
    print(op, f'correction factor: {R_linear_comb_correction_values[i]}')


0.5249181768963586 [] correction factor: 1
0.6527833916355477 [Z1 Y2] correction factor: (-0-1j)
0.33982846654021914 [Y1] correction factor: (-0-1j)
0.42761123055588435 [Z0 X1 Y2] correction factor: 1j


In [82]:
### checking reduction
from openfermion.ops import QubitOperator
from openfermion.utils import hermitian_conjugated

Hsl = QubitOperator()
for op in largest_AC_set:
    Hsl+=op


### R op without phase absorbed!
R = QubitOperator()
for op in R_linear_comb_list:
    R+=op


print(R*Hsl*hermitian_conjugated(R))
print(Pn * gamma_l)
print('')

### R op WITH phase absorbed!

R_corr = QubitOperator()
for ind, op in enumerate(R_linear_comb_corrected_phase_OP_list):
    phase = R_linear_comb_correction_values[ind]
    R_corr+=op*phase
    
print(R_corr*Hsl*hermitian_conjugated(R_corr))
print(Pn * gamma_l)

(0.05249943127273581+0j) [X0 X1]
0.052499431272735805 [X0 X1]

(0.05249943127273581+0j) [X0 X1]
0.052499431272735805 [X0 X1]


# 5. Checking custom cirq gate functions

### 5.1 Ansatz

In [83]:
qubits = list(cirq.LineQubit.range(N_qubits))

ansatz = cirq.Circuit([cirq.X.on(q) for q in qubits])
ansatz

0: ───X───

1: ───X───

2: ───X───

### 5.2 full LCU circuit!

In [84]:
from quchem.Unitary_Partitioning.LCU_circuit_functions import Full_LCU_Rl_Circuit


circuit = Full_LCU_Rl_Circuit(Pn,
                         R_linear_comb_corrected_phase_OP_list,
                         R_linear_comb_correction_values,
                         ancilla_amplitudes,
                         N_qubits,
                         ansatz,
                         check_G_circuit=True)

circuit

0: ───X──────────────────────────────────I────────────I────────────1j*Z0───Ry(-0.5π)──────────────────────────────────M───
                                         │            │            │                                                  │
1: ───X──────────────────────────────────(-0-1j)*Z1───(-0-1j)*Y1───X1──────Ry(-0.5π)──────────────────────────────────M───
                                         │            │            │                                                  │
2: ───X──────────────────────────────────Y2───────────┼────────────Y2─────────────────────────────────────────────────┼───
                                         │            │            │                                                  │
3: ───Ry(0.432π)───X───Ry(-0.001π)───X───(0)──────────@────────────@───────X───────────Ry(0.001π)───X───Ry(-0.432π)───M───
                   │                 │   │            │            │       │                        │                 │
4: ───Ry(0.535π)───@─────────────────@───@────────────(0)──────────@───────@────────────────────────@───Ry(-0.535π)───M───

### 5.3 Checking GUGdag = Rl

In [85]:
from quchem.Qcircuit.Circuit_functions_to_create_arb_state import intialization_circuit
from quchem.Unitary_Partitioning.LCU_circuit_functions import LCU_R_gate

check_G_circuit=True
N_system_qubits = N_qubits
N_ancilla = np.log2(len(ancilla_amplitudes))
if np.ceil(N_ancilla) != np.floor(N_ancilla):
    N_ancilla = int(np.ceil(N_ancilla))
    full_ancilla = np.zeros(2**N_ancilla)
    full_ancilla[:len(ancilla_amplitudes)] = np.array(ancilla_amplitudes)
    ancilla_amplitudes= full_ancilla.tolist()
###


N_ancilla = int(np.log2(len(ancilla_amplitudes)))
G_circ = intialization_circuit(ancilla_amplitudes,
                             N_system_qubits,
                             N_system_qubits+N_ancilla-1,
                             check_circuit=check_G_circuit)
G_dagger_circ = cirq.inverse(G_circ)

R_circ_obj = LCU_R_gate(N_ancilla, N_system_qubits, R_linear_comb_corrected_phase_OP_list, R_linear_comb_correction_values, Pn)
R_circ_circ = cirq.Circuit(
    cirq.decompose_once((R_circ_obj(*cirq.LineQubit.range(R_circ_obj.num_qubits())))))

In [86]:
G_circ

3: ───Ry(0.432π)───X───Ry(-0.001π)───X───
                   │                 │
4: ───Ry(0.535π)───@─────────────────@───

In [87]:
print(ancilla_amplitudes)

s=cirq.Simulator()
results=s.simulate(G_circ)
results.state_vector()

[0.5194816750235991, 0.5793072644074639, 0.417978847537169, 0.46886625569656476]


array([0.51948166+0.j, 0.5793073 +0.j, 0.41797882+0.j, 0.46886626+0.j],
      dtype=complex64)

In [88]:
np.allclose(results.state_vector(), np.array(ancilla_amplitudes))

True

In [89]:
G_dagger_circ

3: ───X───Ry(0.001π)───X───Ry(-0.432π)───
      │                │
4: ───@────────────────@───Ry(-0.535π)───

In [90]:
R_circ_circ

0: ───I────────────I────────────1j*Z0───
      │            │            │
1: ───(-0-1j)*Z1───(-0-1j)*Y1───X1──────
      │            │            │
2: ───Y2───────────┼────────────Y2──────
      │            │            │
3: ───(0)──────────@────────────@───────
      │            │            │
4: ───@────────────(0)──────────@───────

In [91]:
# print(cirq.Circuit(cirq.decompose(R_circ_circ)))

In [92]:
I_sys = np.eye(2**N_system_qubits)

I_sys_G_mat = np.kron(I_sys, G_circ.unitary())
U_LCU_mat = R_circ_circ.unitary()
I_sys_G_dag_mat = np.kron(I_sys, G_dagger_circ.unitary())

In [93]:
# G_U_G_dag = np.dot(I_sys_G_mat.dot(U_LCU_mat), I_sys_G_dag_mat)
# G_U_G_dag = np.dot(I_sys_G_dag_mat.dot(U_LCU_mat), I_sys_G_mat)

G_U_G_dag = I_sys_G_mat @ U_LCU_mat @ I_sys_G_dag_mat

G_U_G_dag

array([[0.26986121+0.j, 0.30093951+0.j, 0.21713235+0.j, ...,
        0.        +0.j, 0.        +0.j, 0.        +0.j],
       [0.30093951+0.j, 0.33559691+0.j, 0.24213818+0.j, ...,
        0.        +0.j, 0.        +0.j, 0.        +0.j],
       [0.21713235+0.j, 0.24213818+0.j, 0.17470632+0.j, ...,
        0.        +0.j, 0.        +0.j, 0.        +0.j],
       ...,
       [0.        +0.j, 0.        +0.j, 0.        +0.j, ...,
        0.33559691+0.j, 0.24213818+0.j, 0.27161763+0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, ...,
        0.24213818+0.j, 0.17470632+0.j, 0.19597618+0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, ...,
        0.27161763+0.j, 0.19597618+0.j, 0.21983557+0.j]])

In [94]:
from functools import reduce

ancilla_0_state = reduce(np.kron, [np.array([[1],[0]]) for _ in range(N_ancilla)])
ancilla_0_projector = np.outer(ancilla_0_state, ancilla_0_state)

POVM_0_ancilla = np.kron(I_sys, ancilla_0_projector) # forces all zero measurement on ancilla!

projected_GUG = POVM_0_ancilla.dot(G_U_G_dag)
# projected_GUG = POVM_0_ancilla @ G_U_G_dag @ POVM_0_ancilla.conj().T
# projected_GUG= projected_GUG/np.trace(projected_GUG)

trace_GUG = projected_GUG.reshape([2 ** N_system_qubits, 2 ** N_ancilla,
                                                2 ** N_system_qubits, 2 ** N_ancilla])
reduced_MAT = np.einsum('jiki->jk', trace_GUG)
reduced_MAT*l1_norm

array([[ 0.52491818+0.j, -0.65582073+0.j, -0.33982847+0.j,
         0.42457389+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.65582073+0.j,  0.52491818+0.j, -0.42457389+0.j,
        -0.33982847+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.33982847+0.j,  0.42457389+0.j,  0.52491818+0.j,
         0.65582073+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [-0.42457389+0.j,  0.33982847+0.j, -0.65582073+0.j,
         0.52491818+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.52491818+0.j, -0.65582073+0.j,
        -0.33982847+0.j, -0.42457389+0.j],
       [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.65582073+0.j,  0.52491818+0.j,
         0.42457389+0.j, -0.33982847+0.j],
       [ 0.        +0.j,  0.      

In [95]:
from openfermion.ops import QubitOperator
Rl = QubitOperator()
for op in R_linear_comb_list:
    Rl+=op
Rl

0.5249181768963586 [] +
0.42761123055588435j [Z0 X1 Y2] +
-0.33982846654021914j [Y1] +
-0.6527833916355477j [Z1 Y2]

In [96]:
from openfermion import qubit_operator_sparse
Rl_mat = qubit_operator_sparse(Rl, n_qubits = N_system_qubits)
Rl_mat.todense()

matrix([[ 0.52491818+0.j, -0.65278339+0.j, -0.33982847+0.j,
          0.42761123+0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j],
        [ 0.65278339+0.j,  0.52491818+0.j, -0.42761123+0.j,
         -0.33982847+0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j],
        [ 0.33982847+0.j,  0.42761123+0.j,  0.52491818+0.j,
          0.65278339+0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j],
        [-0.42761123+0.j,  0.33982847+0.j, -0.65278339+0.j,
          0.52491818+0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j],
        [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.52491818+0.j, -0.65278339+0.j,
         -0.33982847+0.j, -0.42761123+0.j],
        [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.65278339+0.j,  0.52491818+0.j,
          0.42761123+0.j, -0.33982847+0.j],
        [ 0.    

In [97]:
Rl_mat.todense() == reduced_MAT*l1_norm

matrix([[ True, False, False, False,  True,  True,  True,  True],
        [False,  True, False, False,  True,  True,  True,  True],
        [False, False,  True, False,  True,  True,  True,  True],
        [False, False, False,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True, False, False, False],
        [ True,  True,  True,  True, False,  True, False, False],
        [ True,  True,  True,  True, False, False,  True, False],
        [ True,  True,  True,  True, False, False, False,  True]])

In [32]:
# np.allclose(Rl_mat.todense(), reduced_MAT*l1_norm)

In [98]:
np.where(reduced_MAT*l1_norm != Rl_mat.todense())

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
        7, 7]),
 array([1, 2, 3, 0, 2, 3, 0, 1, 3, 0, 1, 2, 5, 6, 7, 4, 6, 7, 4, 5, 7, 4,
        5, 6]))

In [99]:
A = reduced_MAT*l1_norm
B = Rl_mat.todense()

In [100]:
i=7
j=6
print(A[i,j])
print(B[i,j])

(-0.6558207305154462+0j)
(-0.6527833916355477+0j)


In [101]:
### checking reduction
from openfermion.ops import QubitOperator
from openfermion.utils import hermitian_conjugated
from openfermion import qubit_operator_sparse

N_qubits = 3
Hsl = QubitOperator()
for op in largest_AC_set:
    Hsl+=op
Hsl_mat = qubit_operator_sparse(Hsl, n_qubits = N_qubits)
### R op without phase absorbed!
Rl = QubitOperator()
for op in R_linear_comb_list:
    Rl+=op
Rl_mat = qubit_operator_sparse(Rl, n_qubits = N_qubits)
Pn_mat = qubit_operator_sparse(Pn, n_qubits = N_qubits)


out1 = Rl_mat@Hsl_mat@hermitian_conjugated(Rl_mat)
np.allclose(out1.todense(), Pn_mat.todense()* gamma_l)

True

In [102]:
proj_mat = reduced_MAT*l1_norm
out2 = proj_mat@Hsl_mat@hermitian_conjugated(proj_mat)
np.allclose(out2, Pn_mat.todense()* gamma_l)

False

In [103]:
np.around(out1.todense(), 3)

matrix([[ 0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j, -0.   +0.j,
          0.   +0.j,  0.052+0.j,  0.   +0.j],
        [ 0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j, -0.   +0.j,
         -0.   +0.j,  0.   +0.j,  0.052+0.j],
        [ 0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j,  0.052+0.j,
         -0.   +0.j,  0.   +0.j,  0.   +0.j],
        [ 0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j,
          0.052+0.j, -0.   +0.j,  0.   +0.j],
        [-0.   +0.j, -0.   +0.j,  0.052+0.j, -0.   +0.j,  0.   +0.j,
          0.   +0.j,  0.   +0.j,  0.   +0.j],
        [ 0.   +0.j, -0.   +0.j,  0.   +0.j,  0.052+0.j,  0.   +0.j,
          0.   +0.j,  0.   +0.j,  0.   +0.j],
        [ 0.052+0.j, -0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j,
          0.   +0.j,  0.   +0.j,  0.   +0.j],
        [ 0.   +0.j,  0.052+0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j,
          0.   +0.j,  0.   +0.j,  0.   +0.j]])

In [104]:
np.around(out2, 3)

array([[ 0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j,
        -0.   +0.j,  0.053+0.j, -0.   +0.j],
       [ 0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j,
         0.   +0.j,  0.   +0.j,  0.053+0.j],
       [ 0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j,  0.053+0.j,
         0.   +0.j, -0.   +0.j, -0.   +0.j],
       [ 0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j, -0.   +0.j,
         0.053+0.j,  0.   +0.j, -0.   +0.j],
       [ 0.   +0.j,  0.   +0.j,  0.053+0.j, -0.   +0.j,  0.   +0.j,
         0.   +0.j,  0.   +0.j,  0.   +0.j],
       [-0.   +0.j,  0.   +0.j,  0.   +0.j,  0.053+0.j,  0.   +0.j,
         0.   +0.j,  0.   +0.j,  0.   +0.j],
       [ 0.053+0.j,  0.   +0.j, -0.   +0.j,  0.   +0.j,  0.   +0.j,
         0.   +0.j,  0.   +0.j,  0.   +0.j],
       [-0.   +0.j,  0.053+0.j, -0.   +0.j, -0.   +0.j,  0.   +0.j,
         0.   +0.j,  0.   +0.j,  0.   +0.j]])

In [105]:
aniclla_0_state = reduce(np.kron, [np.array([[1],[0]]) for _ in range(N_ancilla)])


bra = np.kron(I_sys, aniclla_0_state.conj().T)
ket = np.kron(I_sys, aniclla_0_state)

traced_R = bra @ G_U_G_dag @ ket *l1_norm

In [106]:
traced_R

array([[ 0.52491818+0.j, -0.65582073+0.j, -0.33982847+0.j,
         0.42457389+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.65582073+0.j,  0.52491818+0.j, -0.42457389+0.j,
        -0.33982847+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.33982847+0.j,  0.42457389+0.j,  0.52491818+0.j,
         0.65582073+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [-0.42457389+0.j,  0.33982847+0.j, -0.65582073+0.j,
         0.52491818+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.52491818+0.j, -0.65582073+0.j,
        -0.33982847+0.j, -0.42457389+0.j],
       [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.65582073+0.j,  0.52491818+0.j,
         0.42457389+0.j, -0.33982847+0.j],
       [ 0.        +0.j,  0.      

In [107]:
Rl_mat.todense()

matrix([[ 0.52491818+0.j, -0.65278339+0.j, -0.33982847+0.j,
          0.42761123+0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j],
        [ 0.65278339+0.j,  0.52491818+0.j, -0.42761123+0.j,
         -0.33982847+0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j],
        [ 0.33982847+0.j,  0.42761123+0.j,  0.52491818+0.j,
          0.65278339+0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j],
        [-0.42761123+0.j,  0.33982847+0.j, -0.65278339+0.j,
          0.52491818+0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j],
        [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.52491818+0.j, -0.65278339+0.j,
         -0.33982847+0.j, -0.42761123+0.j],
        [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.65278339+0.j,  0.52491818+0.j,
          0.42761123+0.j, -0.33982847+0.j],
        [ 0.    

In [108]:
np.allclose(Rl_mat.todense(), bra @ G_U_G_dag @ ket *l1_norm)

False

TODO: need to check why there is a difference. Likely due to numerical effects with approximations of G and G_dag!

CHANGE which anti-commuting set is used!
aka seems to work fully when set 7 is chosen!


In [109]:
G_circ.final_state_vector()

array([0.51948168+0.j, 0.57930726+0.j, 0.41797885+0.j, 0.46886626+0.j])