In [1]:
import os
import ast
import cirq
import numpy as np

In [2]:
### open Hamiltonian data ###

working_dir = os.getcwd()
parent_dir = os.path.dirname(working_dir) # gets directory where running python file is!

data_dir = os.path.join(parent_dir, 'Molecular_Hamiltonian_data')
hamiltonian_data = os.path.join(data_dir, 'hamiltonians.txt')

In [3]:
with open(hamiltonian_data, 'r') as input_file:
    hamiltonians = ast.literal_eval(input_file.read())

for key in hamiltonians.keys():
    print(f"{key: <25}     n_qubits:  {hamiltonians[key][1]:<5.0f}")

H2-S1_STO-3G_singlet          n_qubits:  18   
C1-O1_STO-3G_singlet          n_qubits:  16   
H1-Cl1_STO-3G_singlet         n_qubits:  16   
H1-Na1_STO-3G_singlet         n_qubits:  16   
H2-Mg1_STO-3G_singlet         n_qubits:  17   
H1-F1_3-21G_singlet           n_qubits:  18   
H1-Li1_3-21G_singlet          n_qubits:  18   
Be1_STO-3G_singlet            n_qubits:  5    
H1-F1_STO-3G_singlet          n_qubits:  8    
H1-Li1_STO-3G_singlet         n_qubits:  8    
Ar1_STO-3G_singlet            n_qubits:  13   
F2_STO-3G_singlet             n_qubits:  15   
H1-O1_STO-3G_singlet          n_qubits:  8    
H2-Be1_STO-3G_singlet         n_qubits:  9    
H2-O1_STO-3G_singlet          n_qubits:  10   
H2_3-21G_singlet              n_qubits:  5    
H2_6-31G_singlet              n_qubits:  5    
H3-N1_STO-3G_singlet          n_qubits:  13   
H4-C1_STO-3G_singlet          n_qubits:  14   
Mg1_STO-3G_singlet            n_qubits:  13   
N2_STO-3G_singlet             n_qubits:  15   
Ne1_STO-3G_si

In [4]:
molecule_key = 'H3_STO-3G_singlet_1+'
transformation, N_qubits, Hamilt_dictionary, _ ,_, _ = hamiltonians[molecule_key]

# 1. Get OpenFermion representation of Hamiltonian

In [5]:
from quchem.Misc_functions.conversion_scripts import Get_Openfermion_Hamiltonian

openFermion_H = Get_Openfermion_Hamiltonian(Hamilt_dictionary)
openFermion_H

-1.7512307459285525 [] +
0.01872992170537467 [X0] +
-0.023568139980123585 [X0 X1] +
0.03597868636603963 [X0 X1 X2] +
-0.023568139980123585 [X0 X1 Z2] +
-0.03597868636603963 [X0 Y1 Y2] +
0.01872992170537467 [X0 Z1] +
0.023568139980123585 [X0 Z1 X2] +
0.01872992170537467 [X0 Z1 Z2] +
0.023568139980123585 [X0 X2] +
0.01872992170537467 [X0 Z2] +
0.03597868636603963 [Y0 X1 Y2] +
-0.023568139980123585 [Y0 Y1] +
0.03597868636603963 [Y0 Y1 X2] +
-0.023568139980123585 [Y0 Y1 Z2] +
0.023568139980123585 [Y0 Z1 Y2] +
0.023568139980123585 [Y0 Y2] +
-0.45436486525596403 [Z0] +
0.02356815233618002 [Z0 X1] +
0.02356815233617983 [Z0 X1 Z2] +
-0.07195737217001562 [Z0 Y1 Y2] +
0.37110605476609804 [Z0 Z1] +
-0.023568152336179825 [Z0 Z1 X2] +
-0.2878474382772282 [Z0 Z1 Z2] +
-0.023568152336180023 [Z0 X2] +
0.37110605476609787 [Z0 Z2] +
0.02356815233618002 [X1] +
0.02356815233617983 [X1 Z2] +
-0.07195737217001562 [Y1 Y2] +
-0.017109477140260287 [Z1] +
-0.023568152336179825 [Z1 X2] +
0.31270210682950855 [Z1 

# 2. Get cliques defined by commutativity 


In [6]:
from quchem.Unitary_Partitioning.Graph import Clique_cover_Hamiltonian

commutativity_flag = 'AC' ## <- defines relationship between sets!!!
Graph_colouring_strategy='largest_first'


anti_commuting_sets = Clique_cover_Hamiltonian(openFermion_H, 
                                                     N_qubits, 
                                                     commutativity_flag, 
                                                     Graph_colouring_strategy)
anti_commuting_sets

{0: [-1.7512307459285525 []],
 1: [-0.017109477140260287 [Z2],
  -0.023568152336179825 [Z1 X2],
  0.03597868636603963 [X0 X1 X2],
  0.023568139980123585 [Y0 Z1 Y2]],
 2: [0.02356815233617983 [X1 Z2],
  -0.017109477140260287 [Z1],
  0.03597868636603963 [Y0 X1 Y2],
  -0.023568139980123585 [Y0 Y1]],
 3: [0.37110605476609787 [Z0 Z2],
  -0.023568152336179825 [Z0 Z1 X2],
  0.01872992170537467 [X0],
  -0.023568139980123585 [Y0 Y1 Z2]],
 4: [0.02356815233617983 [Z0 X1 Z2],
  0.37110605476609804 [Z0 Z1],
  0.01872992170537467 [X0 Z2],
  0.023568139980123585 [X0 Z1 X2]],
 5: [0.023568139980123585 [X0 X2],
  -0.023568139980123585 [X0 X1 Z2],
  0.01872992170537467 [X0 Z1 Z2],
  0.03597868636603963 [Y0 Y1 X2],
  -0.45436486525596403 [Z0]],
 6: [-0.023568139980123585 [X0 X1],
  -0.03597868636603963 [X0 Y1 Y2],
  0.01872992170537467 [X0 Z1],
  0.023568139980123585 [Y0 Y2]],
 7: [-0.023568152336180023 [X2], -0.07195737217001562 [Y1 Y2]],
 8: [0.02356815233618002 [X1], 0.31270210682950855 [Z1 Z2]],
 9:

# 3. Example of R_l operator

In [262]:
key_larg, largest_AC_set = max(anti_commuting_sets.items(), key=lambda x:len(x[1])) # largest nonCon part found by dfs alg
largest_AC_set

[0.023568139980123585 [X0 X2],
 -0.023568139980123585 [X0 X1 Z2],
 0.01872992170537467 [X0 Z1 Z2],
 0.03597868636603963 [Y0 Y1 X2],
 -0.45436486525596403 [Z0]]

In [273]:
## works with:
key=6 #7
key_larg, largest_AC_set = key, anti_commuting_sets[key]

In [274]:
from quchem.Unitary_Partitioning.Unitary_partitioning_LCU_method import Get_R_op_list

N_index=0
check_reduction = True

R_linear_comb_list, Pn, gamma_l = Get_R_op_list(largest_AC_set,
                                                N_index,
                                                N_qubits,
                                                check_reduction=check_reduction, 
                                                atol=1e-8,
                                                rtol=1e-05)

R_linear_comb_list

[0.5249181768963586 [],
 (-0-0.6527833916355477j) [Z1 Y2],
 (-0-0.33982846654021914j) [Y1],
 0.42761123055588435j [Z0 X1 Y2]]

To perform Unitary Partitioning via a LCU - apply the linear combination of operators in ```R_linear_comb_list```

- in Q circuit form these all must have real amplitudes
- and be l1 normalized

In [275]:
from quchem.Unitary_Partitioning.LCU_circuit_functions import absorb_complex_phases
R_linear_comb_corrected_phase_OP_list, R_linear_comb_correction_values, ancilla_amplitudes, l1_norm = absorb_complex_phases(R_linear_comb_list)

for i, op in enumerate(R_linear_comb_corrected_phase_OP_list):
    print(op, f'correction factor: {R_linear_comb_correction_values[i]}')


0.5194816750235991 [] correction factor: 1
0.5793072644074639 [Z1 Y2] correction factor: (-0-1j)
0.417978847537169 [Y1] correction factor: (-0-1j)
0.46886625569656476 [Z0 X1 Y2] correction factor: 1j


# 4. Checking custom cirq gate functions

### 4.1 Ansatz

In [276]:
qubits = list(cirq.LineQubit.range(N_qubits))

ansatz = cirq.Circuit([cirq.X.on(q) for q in qubits])
ansatz

0: ───X───

1: ───X───

2: ───X───

### 4.2 full LCU circuit!

In [277]:
from quchem.Unitary_Partitioning.LCU_circuit_functions import Full_LCU_Rl_Circuit


circuit = Full_LCU_Rl_Circuit(Pn,
                         R_linear_comb_corrected_phase_OP_list,
                         R_linear_comb_correction_values,
                         ancilla_amplitudes,
                         N_qubits,
                         ansatz,
                         check_G_circuit=True)

circuit

0: ───X──────────────────────────────────I────────────I────────────1j*Z0───Ry(-0.5π)──────────────────────────────────M───
                                         │            │            │                                                  │
1: ───X──────────────────────────────────(-0-1j)*Z1───(-0-1j)*Y1───X1──────Ry(-0.5π)──────────────────────────────────M───
                                         │            │            │                                                  │
2: ───X──────────────────────────────────Y2───────────┼────────────Y2─────────────────────────────────────────────────┼───
                                         │            │            │                                                  │
3: ───Ry(0.432π)───X───Ry(-0.001π)───X───(0)──────────@────────────@───────X───────────Ry(0.001π)───X───Ry(-0.432π)───M───
                   │                 │   │            │            │       │                        │                 │
4: ───Ry(0.535π)───@─────────────────@───@────────────(0)──────────@───────@────────────────────────@───Ry(-0.535π)───M───

### 4.3 Checking GUGdag = Rl

In [278]:
from quchem.Qcircuit.Circuit_functions_to_create_arb_state import intialization_circuit
from quchem.Unitary_Partitioning.LCU_circuit_functions import LCU_R_gate

check_G_circuit=True
N_system_qubits = N_qubits
N_ancilla = np.log2(len(ancilla_amplitudes))
if np.ceil(N_ancilla) != np.floor(N_ancilla):
    N_ancilla = int(np.ceil(N_ancilla))
    full_ancilla = np.zeros(2**N_ancilla)
    full_ancilla[:len(ancilla_amplitudes)] = np.array(ancilla_amplitudes)
    ancilla_amplitudes= full_ancilla.tolist()
###


N_ancilla = int(np.log2(len(ancilla_amplitudes)))
G_circ = intialization_circuit(ancilla_amplitudes,
                             N_system_qubits,
                             N_system_qubits+N_ancilla-1,
                             check_circuit=check_G_circuit)
G_dagger_circ = cirq.inverse(G_circ)

R_circ_obj = LCU_R_gate(N_ancilla, N_system_qubits, R_linear_comb_corrected_phase_OP_list, R_linear_comb_correction_values, Pn)
R_circ_circ = cirq.Circuit(
    cirq.decompose_once((R_circ_obj(*cirq.LineQubit.range(R_circ_obj.num_qubits())))))

In [279]:
G_circ

3: ───Ry(0.432π)───X───Ry(-0.001π)───X───
                   │                 │
4: ───Ry(0.535π)───@─────────────────@───

In [280]:
G_dagger_circ

3: ───X───Ry(0.001π)───X───Ry(-0.432π)───
      │                │
4: ───@────────────────@───Ry(-0.535π)───

In [281]:
R_circ_circ

0: ───I────────────I────────────1j*Z0───
      │            │            │
1: ───(-0-1j)*Z1───(-0-1j)*Y1───X1──────
      │            │            │
2: ───Y2───────────┼────────────Y2──────
      │            │            │
3: ───(0)──────────@────────────@───────
      │            │            │
4: ───@────────────(0)──────────@───────

In [282]:
I_sys = np.eye(2**N_system_qubits)

I_sys_G_mat = np.kron(I_sys, G_circ.unitary())
U_LCU_mat = R_circ_circ.unitary()
I_sys_G_dag_mat = np.kron(I_sys, G_dagger_circ.unitary())

In [283]:
# G_U_G_dag = np.dot(I_sys_G_mat.dot(U_LCU_mat), I_sys_G_dag_mat)
# G_U_G_dag = np.dot(I_sys_G_dag_mat.dot(U_LCU_mat), I_sys_G_mat)

G_U_G_dag = I_sys_G_mat @ U_LCU_mat @ I_sys_G_dag_mat

G_U_G_dag

array([[0.26986121+0.j, 0.30093951+0.j, 0.21713235+0.j, ...,
        0.        +0.j, 0.        +0.j, 0.        +0.j],
       [0.30093951+0.j, 0.33559691+0.j, 0.24213818+0.j, ...,
        0.        +0.j, 0.        +0.j, 0.        +0.j],
       [0.21713235+0.j, 0.24213818+0.j, 0.17470632+0.j, ...,
        0.        +0.j, 0.        +0.j, 0.        +0.j],
       ...,
       [0.        +0.j, 0.        +0.j, 0.        +0.j, ...,
        0.33559691+0.j, 0.24213818+0.j, 0.27161763+0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, ...,
        0.24213818+0.j, 0.17470632+0.j, 0.19597618+0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, ...,
        0.27161763+0.j, 0.19597618+0.j, 0.21983557+0.j]])

In [284]:
from functools import reduce

ancilla_0_state = reduce(np.kron, [np.array([[1],[0]]) for _ in range(N_ancilla)])
ancilla_0_projector = np.outer(ancilla_0_state, ancilla_0_state)

POVM_0_ancilla = np.kron(I_sys, ancilla_0_projector) # forces all zero measurement on ancilla!

projected_GUG = POVM_0_ancilla.dot(G_U_G_dag)
# projected_GUG = POVM_0_ancilla @ G_U_G_dag @ POVM_0_ancilla

trace_GUG = projected_GUG.reshape([2 ** N_system_qubits, 2 ** N_ancilla,
                                                2 ** N_system_qubits, 2 ** N_ancilla])
reduced_MAT = np.einsum('jiki->jk', trace_GUG)
reduced_MAT*l1_norm

array([[ 0.52491818+0.j, -0.65582073+0.j, -0.33982847+0.j,
         0.42457389+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.65582073+0.j,  0.52491818+0.j, -0.42457389+0.j,
        -0.33982847+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.33982847+0.j,  0.42457389+0.j,  0.52491818+0.j,
         0.65582073+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [-0.42457389+0.j,  0.33982847+0.j, -0.65582073+0.j,
         0.52491818+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.52491818+0.j, -0.65582073+0.j,
        -0.33982847+0.j, -0.42457389+0.j],
       [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.65582073+0.j,  0.52491818+0.j,
         0.42457389+0.j, -0.33982847+0.j],
       [ 0.        +0.j,  0.      

In [285]:
l1_norm

1.9451412656280098

In [286]:
from openfermion.ops import QubitOperator
Rl = QubitOperator()
for op in R_linear_comb_list:
    Rl+=op
Rl

0.5249181768963586 [] +
0.42761123055588435j [Z0 X1 Y2] +
-0.33982846654021914j [Y1] +
-0.6527833916355477j [Z1 Y2]

In [287]:
from openfermion import qubit_operator_sparse
Rl_mat = qubit_operator_sparse(Rl, n_qubits = N_system_qubits)
Rl_mat.todense()#/l1_norm

matrix([[ 0.52491818+0.j, -0.65278339+0.j, -0.33982847+0.j,
          0.42761123+0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j],
        [ 0.65278339+0.j,  0.52491818+0.j, -0.42761123+0.j,
         -0.33982847+0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j],
        [ 0.33982847+0.j,  0.42761123+0.j,  0.52491818+0.j,
          0.65278339+0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j],
        [-0.42761123+0.j,  0.33982847+0.j, -0.65278339+0.j,
          0.52491818+0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.        +0.j],
        [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.52491818+0.j, -0.65278339+0.j,
         -0.33982847+0.j, -0.42761123+0.j],
        [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
          0.        +0.j,  0.65278339+0.j,  0.52491818+0.j,
          0.42761123+0.j, -0.33982847+0.j],
        [ 0.    

In [288]:
aniclla_0_state = reduce(np.kron, [np.array([[1],[0]]) for _ in range(N_ancilla)])


bra = np.kron(I_sys, aniclla_0_state.conj().T)
ket = np.kron(I_sys, aniclla_0_state)

In [289]:
bra @ G_U_G_dag @ ket *l1_norm

array([[ 0.52491818+0.j, -0.65582073+0.j, -0.33982847+0.j,
         0.42457389+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.65582073+0.j,  0.52491818+0.j, -0.42457389+0.j,
        -0.33982847+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.33982847+0.j,  0.42457389+0.j,  0.52491818+0.j,
         0.65582073+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [-0.42457389+0.j,  0.33982847+0.j, -0.65582073+0.j,
         0.52491818+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.52491818+0.j, -0.65582073+0.j,
        -0.33982847+0.j, -0.42457389+0.j],
       [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.65582073+0.j,  0.52491818+0.j,
         0.42457389+0.j, -0.33982847+0.j],
       [ 0.        +0.j,  0.      

In [301]:
np.allclose(Rl_mat.todense(), bra @ G_U_G_dag @ ket *l1_norm, 1e-2)

True

In [302]:
np.allclose(Rl_mat.todense(), bra @ G_U_G_dag @ ket *l1_norm)

False

TODO: need to check why there is a difference. Likely due to numerical effects with approximations of G and G_dag!

CHANGE which anti-commuting set is used!
aka seems to work fully when set 7 is chosen!


In [303]:
G_circ.final_state_vector()

array([0.51948168+0.j, 0.57930726+0.j, 0.41797885+0.j, 0.46886626+0.j])

In [304]:
ancilla_amplitudes

[0.5194816750235991,
 0.5793072644074639,
 0.417978847537169,
 0.46886625569656476]