Follows pg 14 of: https://arxiv.org/pdf/quant-ph/0406176v5.pdf

This is what Qiskit uses

https://quantumcomputing.stackexchange.com/questions/6755/controlled-initialize-instruction

In [1]:
from quchem.Qcircuit.misc_quantum_circuit_functions import Get_state_as_str
import numpy as np
import cirq

In [2]:
state_vec = [np.sqrt(0.9),np.sqrt(0.05), 0 , 0, 0 , 0, 0 , np.sqrt(0.05)]

n_qubits = int(np.log2(len(state_vec)))
print('N_qubits =', n_qubits)
for i, amp in enumerate(state_vec):
    print(Get_state_as_str(n_qubits, i), amp)
    

N_qubits = 3
000 0.9486832980505138
001 0.22360679774997896
010 0
011 0
100 0
101 0
110 0
111 0.22360679774997896


In [3]:
from quchem.Qcircuit.Circuit_functions_to_create_arb_state import intialization_circuit
start_qubit_ind = 0
end_qubit_ind = n_qubits-1 #index from 0

circuit = intialization_circuit(state_vec, start_qubit_ind, end_qubit_ind, check_circuit=True)

s=cirq.Simulator()
results=s.simulate(circuit)
# results=s.simulate(circuit, qubit_order=list(cirq.LineQubit.range(end_qubit_ind,start_qubit_ind-1,-1)))
print(results)

results.state_vector()

measurements: (no measurements)
output vector: 0.949|000⟩ + 0.224|001⟩ + 0.224|111⟩


array([ 9.4868314e-01+0.j,  2.2360674e-01+0.j,  2.9802321e-08+0.j,
        0.0000000e+00+0.j,  0.0000000e+00+0.j,  0.0000000e+00+0.j,
       -8.8817842e-16+0.j,  2.2360675e-01+0.j], dtype=complex64)

In [4]:
np.around(results.state_vector(), 3)

array([ 0.949+0.j,  0.224+0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j,
        0.   +0.j, -0.   +0.j,  0.224+0.j], dtype=complex64)

In [5]:
np.around(np.array(state_vec, dtype='complex64'),3)

array([0.949+0.j, 0.224+0.j, 0.   +0.j, 0.   +0.j, 0.   +0.j, 0.   +0.j,
       0.   +0.j, 0.224+0.j], dtype=complex64)

In [6]:
np.allclose(np.around(np.array(state_vec, dtype='complex64'), 7),np.around(results.state_vector(), 7))

True

In [7]:
circuit

0: ─────────────────────────────────Ry(0.25π)───X───Ry(-0.25π)───X───Ry(0.25π)───X───Ry(-0.25π)───X───
                                                │                │               │                │
1: ───Ry(0.25π)────X───Ry(-0.25π)───X───────────@────────────────┼───────────────@────────────────┼───
                   │                │                            │                                │
2: ───Ry(0.205π)───@────────────────@────────────────────────────@────────────────────────────────@───

In [8]:
state_vec = [np.sqrt(0.4), np.sqrt(0.3), np.sqrt(0.2), np.sqrt(0.1)]

n_qubits = int(np.log2(len(state_vec)))
print('N_qubits =', n_qubits)
for i, amp in enumerate(state_vec):
    print(Get_state_as_str(n_qubits, i), amp)

    
    
start_qubit_ind = 0
end_qubit_ind = n_qubits-1 #index from 0

circuit = intialization_circuit(state_vec, start_qubit_ind, end_qubit_ind, check_circuit=True)
circuit

N_qubits = 2
00 0.6324555320336759
01 0.5477225575051661
10 0.4472135954999579
11 0.31622776601683794


0: ───Ry(0.363π)───X───Ry(0.029π)───X───
                   │                │
1: ───Ry(0.436π)───@────────────────@───

In [9]:
s=cirq.Simulator()
results=s.simulate(circuit)
print(results)

measurements: (no measurements)
output vector: 0.632|00⟩ + 0.548|01⟩ + 0.447|10⟩ + 0.316|11⟩
