In [1]:
import cirq
import numpy as np

In [2]:
qbits = list(cirq.LineQubit.range(3))

test1 = cirq.Circuit(
cirq.CNOT(qbits[0], qbits[1]),
cirq.H(qbits[0]),
cirq.S(qbits[0]),
cirq.CNOT(qbits[0], qbits[1])
    
)
print(test1)
print()
print()

test2 = cirq.Circuit(
cirq.S(qbits[0]),
cirq.H(qbits[1]),
cirq.CNOT(qbits[1], qbits[0]),
cirq.S(qbits[0])**-1,
cirq.S(qbits[1]),
cirq.H(qbits[0]),
cirq.H(qbits[1]),
cirq.S(qbits[0]),
)
test2

print(test2)

np.allclose(test2.unitary(), test1.unitary())

0: ───@───H───S───@───
      │           │
1: ───X───────────X───


0: ───S───X───S^-1───H───S───
          │
1: ───H───@───S──────H───────


True

In [3]:
qbits = list(cirq.LineQubit.range(3))

test3 = cirq.Circuit(
cirq.CNOT(qbits[0], qbits[1]),
cirq.H(qbits[0]),
cirq.CNOT(qbits[0], qbits[1])
    
)
print(test3)
print()
print()

test4 = cirq.Circuit(
cirq.S(qbits[0]),
cirq.H(qbits[1]),
cirq.CNOT(qbits[1], qbits[0]),
cirq.S(qbits[0])**-1,
cirq.S(qbits[1]),
cirq.H(qbits[0]),
cirq.H(qbits[1]),
)
print(test4)

np.allclose(test3.unitary(), test4.unitary())

0: ───@───H───@───
      │       │
1: ───X───────X───


0: ───S───X───S^-1───H───
          │
1: ───H───@───S──────H───


True

In [4]:
qbits = list(cirq.LineQubit.range(3))

test5 = cirq.Circuit(
cirq.CNOT(qbits[1], qbits[2]),
cirq.CNOT(qbits[0], qbits[1]),
cirq.CNOT(qbits[1], qbits[2])
    
)
print(test5)
print()
print()

test6 = cirq.Circuit(
cirq.CNOT(qbits[0], qbits[1]),
cirq.CNOT(qbits[0], qbits[2]),
)
print(test6)

np.allclose(test5.unitary(), test6.unitary())

0: ───────@───────
          │
1: ───@───X───@───
      │       │
2: ───X───────X───


0: ───@───@───
      │   │
1: ───X───┼───
          │
2: ───────X───


True

In [5]:
qbits = list(cirq.LineQubit.range(3))

test7 = cirq.Circuit(
cirq.CNOT(qbits[0], qbits[1]),
cirq.H(qbits[1]),
cirq.CNOT(qbits[0], qbits[1])
    
)
print(test7)
print()
print()

test8 = cirq.Circuit(
cirq.H(qbits[1]),
cirq.CZ(qbits[0], qbits[1]),
cirq.CNOT(qbits[0], qbits[1])
    
)
print(test8)

np.allclose(test7.unitary(), test8.unitary())

0: ───@───────@───
      │       │
1: ───X───H───X───


0: ───────@───@───
          │   │
1: ───H───@───X───


True

In [6]:
test9 = cirq.Circuit(
cirq.H(qbits[0]),
cirq.S(qbits[0]),
cirq.H(qbits[0]),  
)

print(test9)
print()
print()

test10 = cirq.Circuit(
cirq.XPowGate(exponent=0.5).on(qbits[0]),
)

print(test10)
np.allclose(test9.unitary(), test10.unitary())

0: ───H───S───H───


0: ───X^0.5───


True

In [7]:
test10.unitary()

array([[0.5+0.5j, 0.5-0.5j],
       [0.5-0.5j, 0.5+0.5j]])

In [8]:
cirq.ConvertToCzAndSingleGates().optimize_circuit(circuit=test10)
test10

0: ───X^0.5───

In [9]:
# https://quantumai.google/reference/python/cirq/testing/assert_allclose_up_to_global_phase

desired_matrix = cirq.XPowGate(exponent=0.5)._unitary_()
actual_matrix = cirq.rx(np.pi/2)._unitary_()
# actual_matrix = np.eye(2)

cirq.testing.assert_allclose_up_to_global_phase(
    actual_matrix,
    desired_matrix,
    atol=1e-8,
    verbose=False)

## YES rx(pi/2) is the same as X^0.5 up to a global phase

In [10]:
from scipy.linalg import eig, svd

# val, vec = eig(cirq.X._unitary_())
val, vec = eig(cirq.Y._unitary_())

U,D,Udag = svd(vec)

In [11]:
vec

array([[-0.        -0.70710678j,  0.70710678+0.j        ],
       [ 0.70710678+0.j        ,  0.        -0.70710678j]])

In [12]:
np.around(U @ np.diag(D) @ U.conj().T, 3)

array([[ 1.+0.j, -0.+0.j],
       [-0.-0.j,  1.+0.j]])

In [13]:
val

array([ 1.+0.j, -1.+0.j])

In [14]:
HS = cirq.Circuit(
cirq.H.on(qbits[0]),
cirq.S.on(qbits[0]),
).unitary()
HS

array([[ 0.70710678+0.j        ,  0.70710678+0.j        ],
       [ 0.        +0.70710678j, -0.        -0.70710678j]])

In [15]:
out = cirq.rx(-np.pi/2)._unitary_() @ cirq.Z._unitary_() @ cirq.rx(np.pi/2)._unitary_()
np.around(out,3)

array([[ 0.+0.j,  0.-1.j],
       [ 0.+1.j, -0.+0.j]])

In [16]:
cirq.Y._unitary_()

array([[0.+0.j, 0.-1.j],
       [0.+1.j, 0.+0.j]])

In [17]:
HS = cirq.Circuit(
cirq.H.on(qbits[0]),
cirq.S.on(qbits[0]),
).unitary()

HS_dag = cirq.Circuit(
(cirq.S**-1).on(qbits[0]),
cirq.H.on(qbits[0]),
).unitary()

out = HS @ cirq.Z._unitary_() @ HS_dag
np.around(out,3)

array([[0.+0.j, 0.-1.j],
       [0.+1.j, 0.+0.j]])

In [18]:
cirq.Circuit(
cirq.rx(np.pi/2).on(qbits[0])
).unitary()

array([[0.70710678+0.j        , 0.        -0.70710678j],
       [0.        -0.70710678j, 0.70710678+0.j        ]])

In [19]:
test11 = cirq.Circuit(
cirq.H(qbits[0]),
(cirq.S**-1).on(qbits[0]),
cirq.H(qbits[0]),  
)

print(test11)
print()
print()

test12 = cirq.Circuit(
cirq.XPowGate(exponent=-0.5).on(qbits[0]),
)

print(test12)
np.allclose(test11.unitary(), test12.unitary())

0: ───H───S^-1───H───


0: ───X^-0.5───


True

In [20]:
(cirq.X**-0.5)._unitary_()
(cirq.rx(-np.pi/2))._unitary_()

array([[0.70710678+0.j        , 0.        +0.70710678j],
       [0.        +0.70710678j, 0.70710678+0.j        ]])

In [21]:
# https://quantumai.google/reference/python/cirq/testing/assert_allclose_up_to_global_phase

desired_matrix = cirq.XPowGate(exponent=-0.5)._unitary_()
actual_matrix = cirq.rx(-np.pi/2)._unitary_()
# actual_matrix = np.eye(2)

cirq.testing.assert_allclose_up_to_global_phase(
    actual_matrix,
    desired_matrix,
    atol=1e-8,
    verbose=False)

## YES rx(-pi/2) is the same as X^-0.5 up to a global phase

In [22]:
cirq.rx(np.pi/2)._unitary_()

array([[0.70710678+0.j        , 0.        -0.70710678j],
       [0.        -0.70710678j, 0.70710678+0.j        ]])

In [23]:
test9 = cirq.Circuit(
cirq.rx(1*np.pi/2).on(qbits[0]),
cirq.Y(qbits[0]),
cirq.X(qbits[0]),
cirq.rz(7*np.pi/2).on(qbits[0]),  
)
print(test9)
test9.unitary()

0: ───Rx(0.5π)───Y───X───Rz(-0.5π)───


array([[-0.5+0.5j,  0.5+0.5j],
       [-0.5+0.5j, -0.5-0.5j]])

In [24]:
test10 = cirq.Circuit(
cirq.XPowGate(exponent=0.5).on(qbits[0]),
)

cirq.Circuit(cirq.decompose(test10))

0: ───X^0.5───

In [25]:
cirq.XPowGate(exponent=0.5)._unitary_() 

array([[0.5+0.5j, 0.5-0.5j],
       [0.5-0.5j, 0.5+0.5j]])

In [26]:
cirq.X._unitary_() @ cirq.YPowGate(exponent=-0.5)._unitary_()  

array([[-0.5+0.5j,  0.5-0.5j],
       [ 0.5-0.5j,  0.5-0.5j]])

In [27]:
cirq.rx(np.pi/2)._unitary_()

array([[0.70710678+0.j        , 0.        -0.70710678j],
       [0.        -0.70710678j, 0.70710678+0.j        ]])

In [28]:
cirq.rx(1*np.pi/2)._unitary_() @ cirq.rz(7*np.pi/2)._unitary_()

array([[ 0.5+0.5j, -0.5-0.5j],
       [ 0.5-0.5j,  0.5-0.5j]])

In [29]:
cirq.ry(3*np.pi/2)._unitary_() @ cirq.rz(3*np.pi/2)._unitary_()

array([[ 0.5+0.5j,  0.5-0.5j],
       [-0.5-0.5j,  0.5-0.5j]])

In [30]:
cirq.ry(1*np.pi/2)._unitary_() @ cirq.rx(5*np.pi/2)._unitary_()

array([[-0.5-0.5j,  0.5+0.5j],
       [-0.5+0.5j, -0.5+0.5j]])

In [31]:
cirq.X._unitary_()**0.5

array([[0.+0.j, 1.+0.j],
       [1.+0.j, 0.+0.j]])

In [32]:
qbits = list(cirq.LineQubit.range(5))

c1 = cirq.Circuit(
    

cirq.CNOT(qbits[0], qbits[1]),
cirq.CNOT(qbits[1], qbits[2]),
cirq.CNOT(qbits[2], qbits[3]),
cirq.CNOT(qbits[3], qbits[4]),
cirq.rz(np.pi).on(qbits[4]),
cirq.CNOT(qbits[3], qbits[4]),
cirq.CNOT(qbits[2], qbits[3]),
cirq.CNOT(qbits[1], qbits[2]),
cirq.CNOT(qbits[0], qbits[1]),
)

c2 = cirq.Circuit(
    
cirq.H.on(qbits[3]),
    
cirq.CNOT(qbits[0], qbits[1]),
cirq.CNOT(qbits[1], qbits[2]),
cirq.CNOT(qbits[2], qbits[3]),
cirq.CNOT(qbits[3], qbits[4]),
cirq.rz(np.pi).on(qbits[4]),
cirq.CNOT(qbits[3], qbits[4]),
cirq.CNOT(qbits[2], qbits[3]),
cirq.CNOT(qbits[1], qbits[2]),
cirq.CNOT(qbits[0], qbits[1]),

cirq.H.on(qbits[3]),
)

# CC = cirq.Circuit([c1.all_operations(), c2.all_operations()], strategy=cirq.InsertStrategy.NEW)
CC = cirq.Circuit([c1.all_operations(), c2.all_operations()], strategy=cirq.InsertStrategy.EARLIEST)

blocker =lambda op: op == cirq.CNOT(cirq.LineQubit(0),
                                 cirq.LineQubit(1))

start = {
    cirq.LineQubit(0): 1,
     cirq.LineQubit(1): 2,
     cirq.LineQubit(2): 3,
     cirq.LineQubit(3): 4,
     cirq.LineQubit(4): 5
}
# start = dict(zip(qbits, [0 for _ in range(len(qbits))]))
start = {
    cirq.LineQubit(0): 1,
     cirq.LineQubit(1): 2,
}

CC.reachable_frontier_from(start_frontier=start, is_blocker=blocker)

{cirq.LineQubit(1): 7, cirq.LineQubit(0): 8}

In [33]:
CC

0: ───@───────────────────────────────────@───@───────────────────────────────────@───
      │                                   │   │                                   │
1: ───X───@───────────────────────────@───X───X───@───────────────────────────@───X───
          │                           │           │                           │
2: ───────X───@───────────────────@───X───────────X───@───────────────────@───X───────
              │                   │                   │                   │
3: ───────────X───@───────────@───X───H───────────────X───@───────────@───X───H───────
                  │           │                           │           │
4: ───────────────X───Rz(π)───X───────────────────────────X───Rz(π)───X───────────────

In [34]:
CC.moments[8]

cirq.Moment(
    cirq.CNOT(cirq.LineQubit(0), cirq.LineQubit(1)),
)

In [35]:
qbits = list(cirq.LineQubit.range(5))

CC = cirq.Circuit(
    

cirq.CNOT(qbits[0], qbits[1]),
cirq.CNOT(qbits[1], qbits[2]),
cirq.CNOT(qbits[2], qbits[3]),
cirq.CNOT(qbits[3], qbits[4]),
cirq.rz(np.pi).on(qbits[4]),
cirq.CNOT(qbits[3], qbits[4]),
cirq.CNOT(qbits[2], qbits[3]),
cirq.CNOT(qbits[1], qbits[2]),
cirq.CNOT(qbits[0], qbits[1]),

##
cirq.H.on(qbits[3]),
    
cirq.CNOT(qbits[0], qbits[1]),
cirq.CNOT(qbits[1], qbits[2]),
cirq.CNOT(qbits[2], qbits[3]),
cirq.CNOT(qbits[3], qbits[4]),
cirq.rz(np.pi).on(qbits[4]),
cirq.CNOT(qbits[3], qbits[4]),
cirq.CNOT(qbits[2], qbits[3]),
cirq.CNOT(qbits[1], qbits[2]),
cirq.CNOT(qbits[0], qbits[1]),

cirq.H.on(qbits[3]),
)


blocker =lambda op: op == cirq.CNOT(cirq.LineQubit(0),
                                 cirq.LineQubit(1))

start = {
    cirq.LineQubit(0): 1,
     cirq.LineQubit(1): 2,
     cirq.LineQubit(2): 3,
     cirq.LineQubit(3): 4,
     cirq.LineQubit(4): 5
}
# start = dict(zip(qbits, [0 for _ in range(len(qbits))]))
start = {
    cirq.LineQubit(0): 9
}

CC.reachable_frontier_from(start_frontier=start, is_blocker=blocker)

{cirq.LineQubit(0): 9}

In [36]:
def Get_CNOT_inbetween_terms(Q_circuit, LineQubit1, LineQubit2, left_CNOT_cascade_ind):
    
    start = {
    LineQubit1: left_CNOT_cascade_ind
    }
    
#     blocker =lambda op: op == cirq.CNOT(cirq.LineQubit(0),cirq.LineQubit(1))

    blocker =lambda op: (op.gate == cirq.CNOT and op.qubits == tuple(LineQubit1, LineQubit2))
    
    def blocker(op):
        print(op)
        if (op.gate == cirq.CNOT and op.qubits == tuple(LineQubit1, LineQubit2)):
            return True
        else:
            return False
    
    first_CNOT = Q_circuit.reachable_frontier_from(start_frontier=start, is_blocker=blocker)
    
    second_start = {
    LineQubit1: first_CNOT[LineQubit1]+1
    }
    
    second_CNOT = Q_circuit.reachable_frontier_from(start_frontier=second_start, is_blocker=blocker)
    
    third_start = {
    LineQubit1: second_CNOT[LineQubit1]+1
    }
    
    third_CNOT = Q_circuit.reachable_frontier_from(start_frontier=third_start, is_blocker=blocker)
    
    second_CNOT_moment_ind = second_CNOT[LineQubit1]
    third_CNOT_moment_ind = third_CNOT[LineQubit1]
    if  second_CNOT_moment_ind== third_CNOT_moment_ind-1:
        return True, second_CNOT_moment_ind, third_CNOT_moment_ind
    else:
        return False
    

In [37]:
LL.gate == cirq.CNOT

NameError: name 'LL' is not defined

In [ ]:
CC.moments[8]

In [ ]:
Get_CNOT_inbetween_terms(CC, cirq.LineQubit(0), cirq.LineQubit(1), 0)

In [ ]:
CC.next_moments_operating_on(
    qubits= [cirq.LineQubit(0), cirq.LineQubit(1)],
    start_moment_index=2
)


In [ ]:
CC.moments[7]

In [ ]:
def Get_CNOT_inbetween_terms(Q_circuit, LineQubit1, LineQubit2, left_CNOT_cascade_ind):
    
    first_CNOT = Q_circuit.next_moments_operating_on(
        qubits= [LineQubit1],
        start_moment_index=left_CNOT_cascade_ind
    )
    
    second_start_moment_index = 


In [ ]:
cirq.CNOT(cirq.LineQubit(1), cirq.LineQubit(2)) in CC.moments[7] 

In [ ]:
CC.moments.pop(7)

In [ ]:
from copy import deepcopy as copy

def cancel_CNOTS(Q_circuit):
    Q_circuit_closest = cirq.Circuit(Q_circuit.all_operations(), strategy=cirq.InsertStrategy.EARLIEST)
    
    moment_copy = copy(Q_circuit_closest.moments)
    
    for ind, moment in enumerate(Q_circuit_closest.moments[:-1]):
        
        CNOT=False
        for op_ind, op in enumerate(moment):
            if op.gate == cirq.CNOT:
                next_moment = Q_circuit_closest.moments[ind+1]
                if op in next_moment:
                    ind_match = [j for j, op2 in enumerate(next_moment) if op==op2][0]
                    print(ind_match)
                    del moment_copy[ind][op_ind]
                    del moment_copy[ind+1][ind_match]
        
#         if CNOT is True:
#             for op2_ind, op2 in enumerate(moment_copy[ind+1]):
#                 print(op)
#                 print(op2)
#                 print()
#                 if op2 == gate_taken:
#                     print(moment_copy[ind+1][op2_ind])
#                     print(moment_copy[ind][gate_taken_ind])
                    
#                     del moment_copy[ind+1][op2_ind]
#                     del moment_copy[ind][gate_taken_ind]
#                     Q_circ_update = cirq.Circuit(moment_copy)
#                     return cancel_CNOTS(Q_circ_update)
#         else:
#             continue
    
    return cirq.Circuit(moment_copy)
            
                
    

In [ ]:
cancel_CNOTS(CC)

In [ ]:
test9 = cirq.Circuit(
cirq.H(qbits[0]),
cirq.S(qbits[0])
)
print(test9)
test9.unitary()

In [ ]:
test9 = cirq.Circuit(
cirq.rx(-np.pi/2).on(qbits[0]),
)
print(test9)
test9.unitary()

In [ ]:
test9 = cirq.Circuit(
(cirq.S**-1).on(qbits[0]),
cirq.H(qbits[0]),
cirq.Z(qbits[0]),
cirq.H(qbits[0]),
(cirq.S).on(qbits[0]),
)
print(test9)
test9.unitary()

In [ ]:
test9 = cirq.Circuit(
(cirq.S).on(qbits[0]),
cirq.H(qbits[0]),
cirq.Z(qbits[0]),
cirq.H(qbits[0]),
(cirq.S**-1).on(qbits[0]),
)
print(test9)
test9.unitary()

In [ ]:
cirq.Y._unitary_()

In [ ]:
S_dagH = cirq.Circuit(
(cirq.S**-1).on(qbits[0]),
cirq.H(qbits[0]))._unitary_()

In [ ]:
np.around(S_dagH.conj().T @ cirq.Z._unitary_() @ S_dagH)

In [ ]:
Rx = cirq.Circuit(
cirq.rx(np.pi/2).on(qbits[0])
).unitary()

np.around(Rx.conj().T @ cirq.Z._unitary_() @ Rx)

In [ ]:
test9 = cirq.Circuit(
(cirq.S**-1).on(qbits[0]),
cirq.H(qbits[0]),
cirq.Z(qbits[0]),
cirq.H(qbits[0]),
(cirq.S).on(qbits[0]),
)
print(test9)
test9.unitary()

In [ ]:
test9 = cirq.Circuit(
cirq.rx(-np.pi/2).on(qbits[0]),
cirq.Z(qbits[0]),
cirq.rx(np.pi/2).on(qbits[0])
)
print(test9)
np.around(test9.unitary(),3)

In [ ]:
test9 = cirq.Circuit(
cirq.H(qbits[0]),
cirq.S(qbits[0]),
cirq.H(qbits[0]),
)
print(test9)
test9.unitary()

In [ ]:
import qiskit 

In [ ]:
test10 = cirq.Circuit(
cirq.XPowGate(exponent=0.5).on(qbits[0]),
)
print(test10)
xx = test10.to_qasm(header=False)


# test10 = cirq.Circuit(
# cirq.H.on(qbits[0]),
# cirq.S.on(qbits[0]),
# cirq.H.on(qbits[0]),
# )
# print(test10)
# xx = test10.to_qasm(header=False)

In [ ]:
test10.unitary()

In [ ]:
qbits = list(cirq.LineQubit.range(3))

test3 = cirq.Circuit(
cirq.CNOT(qbits[0], qbits[1]),
(cirq.X**0.5).on(qbits[0]),
cirq.CNOT(qbits[0], qbits[1])
    
)
print(test3)
print()
print()

test4 = cirq.Circuit(
cirq.rz(np.pi/2).on(qbits[0]),
    (cirq.X**0.5).on(qbits[0]),
    (cirq.X**0.5).on(qbits[1]),
    cirq.rz(3*np.pi/2).on(qbits[0]),
cirq.CNOT(qbits[0], qbits[1]),
    (cirq.X**0.5).on(qbits[0]),
cirq.rz(np.pi/2).on(qbits[0]),
)
print(test4)

np.allclose(test3.unitary(), test4.unitary())

In [ ]:
# https://quantumai.google/reference/python/cirq/testing/assert_allclose_up_to_global_phase

cirq.testing.assert_allclose_up_to_global_phase(
    test3.unitary(),
    test4.unitary(),
    atol=1e-8,
    verbose=False)

## YES above circuits are the same up to a global phase

In [ ]:
np.around(test4.unitary(), 3)

In [ ]:
test3.unitary()

In [ ]:
qbits = list(cirq.LineQubit.range(3))

test3 = cirq.Circuit(
cirq.CNOT(qbits[0], qbits[1]),
(cirq.X**0.5).on(qbits[0]),
cirq.CNOT(qbits[0], qbits[1])
    
)
print(test3)
print()
print()


test4 = cirq.Circuit(
(cirq.H).on(qbits[0]),
# (cirq.X**0.5).on(qbits[0]),
cirq.CNOT(qbits[0], qbits[1]),
(cirq.S**1).on(qbits[0]),
# (cirq.X**0.5).on(qbits[0]),
(cirq.H).on(qbits[0]),
    
(cirq.S).on(qbits[0]),
cirq.rz(-np.pi/2).on(qbits[0]),

cirq.rx(np.pi/2).on(qbits[1]),
 
)
print(test4)


cirq.testing.assert_allclose_up_to_global_phase(
    test3.unitary(),
    test4.unitary(),
    atol=1e-8,
    verbose=False)

## YES THESE ARE THE SAME UP TO A GLOBAL PHASE OF e^{+i pi/4}

np.allclose(test3.unitary(), test4.unitary())

In [ ]:
test4_phase = cirq.Circuit(
(cirq.H).on(qbits[0]),
# (cirq.X**0.5).on(qbits[0]),
cirq.CNOT(qbits[0], qbits[1]),
(cirq.S**1).on(qbits[0]),
# (cirq.X**0.5).on(qbits[0]),
(cirq.H).on(qbits[0]),

cirq.rx(np.pi/2).on(qbits[1]),
cirq.MatrixGate(np.eye(4)*np.e**(-1j*-np.pi/4)).on(qbits[0], qbits[1]))

print(test4_phase)

np.allclose(test3.unitary(), test4_phase.unitary())

In [ ]:
cirq.ConvertToCzAndSingleGates().optimize_circuit(circuit=test4_phase) 
np.allclose(test3.unitary(), test4_phase.unitary())

In [ ]:
np.around(test4.unitary(), 3)

In [ ]:
np.around(test4.unitary()* np.e**(-1j*-np.pi/4),  3) == test3.unitary()

In [ ]:
np.around(test4.unitary() @ np.eye(4)*np.e**(-1j*-np.pi/4),3) == test3.unitary()

In [ ]:
cirq.rz(np.pi/2)._unitary_() ==cirq.rz(2*np.pi)._unitary_()

In [ ]:
(cirq.S**-1)._unitary_() @ cirq.rz(np.pi/2)._unitary_()

In [ ]:
np.around(np.eye(4)*np.e**(-1j*-np.pi/4), 3)

In [ ]:

test5 = cirq.Circuit(
    
# (cirq.S**-1).on(qbits[0]),
# (cirq.S**-1).on(qbits[1]),
cirq.rz(-np.pi/4).on(qbits[0]),
cirq.rz(-np.pi/4).on(qbits[1]),
# cirq.H.on(qbits[0]),
# cirq.H.on(qbits[1]),
# (cirq.S**-1).on(qbits[0]),
# (cirq.S**-1).on(qbits[1]),
# (cirq.Z**0.25)(qbits[1]).controlled_by(qbits[0])
# (cirq.H).on(qbits[1]).controlled_by(qbits[0])
)

print(test5)

np.around(test5.unitary(), 3)

In [ ]:

test5 = cirq.Circuit(
    
(cirq.S).on(qbits[0]),
# (cirq.S**-1).on(qbits[1]),
cirq.rz(-np.pi/2).on(qbits[0]),
cirq.I.on(qbits[1]),
)

print(test5)

np.around(test5.unitary(), 3)

In [ ]:
tttt = cirq.MatrixGate(np.eye(4)*np.e**(-1j*-np.pi/4))

In [ ]:
test5 = cirq.Circuit(
     cirq.X.on(qbits[1]),
    cirq.MatrixGate(np.eye(4)*np.e**(-1j*-np.pi/4)).on(qbits[0], qbits[1]),
     cirq.S.on(qbits[0]),
     cirq.S.on(qbits[1]),
     cirq.S.on(qbits[2]),
)
test5

In [ ]:
cirq.ConvertToCzAndSingleGates().optimize_circuit(circuit=test5) 
test5.unitary()

In [ ]:
cirq.rz(np.pi/4)/

In [ ]:
np.around(test4.unitary(), 3)

In [ ]:
qbits = list(cirq.LineQubit.range(3))

test3 = cirq.Circuit(
cirq.CNOT(qbits[0], qbits[1]),
(cirq.X**0.5).on(qbits[0]),
cirq.CNOT(qbits[0], qbits[1])
    
)
print(test3)
print()
print()

test4 = cirq.Circuit(
# cirq.S(qbits[0]),
(cirq.X**-0.5).on(qbits[1]),
    
cirq.H(qbits[0]),   
cirq.CNOT(qbits[1], qbits[0]),
# cirq.H(qbits[0]), 
# cirq.S(qbits[0])**-1,
cirq.S(qbits[1]),
# cirq.H(qbits[0]),
(cirq.X**0.5).on(qbits[0]),
(cirq.X**0.5).on(qbits[1]),
cirq.H(qbits[0]), 
)
print(test4)

np.allclose(test3.unitary(), test4.unitary())

In [ ]:
test3.unitary()

In [ ]:
test4.unitary()

In [ ]:
X @ Xpow == Xpow @ X

In [ ]:
# qbits = list(cirq.LineQubit.range(3))

# test3 = cirq.Circuit(
# cirq.CNOT(qbits[0], qbits[1]),
# (cirq.X**0.5).on(qbits[0]),
# cirq.CNOT(qbits[0], qbits[1])
    
# )
# print(test3)
# print()
# print()

# test4 = cirq.Circuit(
# cirq.S(qbits[0]),
# cirq.H(qbits[1]),
# cirq.CNOT(qbits[1], qbits[0]),
# # cirq.S(qbits[0])**-1,
# cirq.S(qbits[1]),
# # cirq.H(qbits[0]),
# (cirq.X**0.5).on(qbits[0]),
#     cirq.H(qbits[1]),
# )
# print(test4)

# np.allclose(test3.unitary(), test4.unitary())

In [ ]:
import qiskit
from qiskit import QuantumCircuit, Aer, execute

In [ ]:

# From str.
qc = QuantumCircuit.from_qasm_str(xx)
# If you want to read from file, use instead
# qc = QuantumCircuit.from_qasm_file("/path/to/file.qasm")

# You can choose other backend also.
backend = Aer.get_backend("qasm_simulator")

# Execute the circuit and show the result.
# job = execute(qc, backend)
# result = job.result()
# print(result.get_counts())

print(qc)

In [ ]:
new = qiskit.compiler.transpile(qc, optimization_level=3)
new.draw()

In [ ]:
test10.unitary()

In [ ]:
test9 = cirq.Circuit(
cirq.rx(np.pi/2).on(qbits[0]),
).unitary()
test9

In [ ]:
qc = QuantumCircuit(1)
qc.rx(np.pi/2,0)
qc.h(0)
print(qc.draw())

new = qiskit.compiler.transpile(qc, optimization_level=3)
new.draw()

In [ ]:
qbits = list(cirq.LineQubit.range(3))

test3 = cirq.Circuit(
cirq.S(qbits[0])**-1,
(cirq.X**0.5).on(qbits[0]),
cirq.S(qbits[0]),
)
print(test3)
print()
print()

test3.unitary()

In [ ]:
help(qc.h)

In [ ]:
qc = QuantumCircuit(2)
qc.cnot(0,1)
qc.h(0)
qc.cnot(0,1)
print(qc.draw())

# bgates = ['cx', 'u1', 'u2', 'u3']
bgates = ['id', 'rz', 'sx', 'x', 'cx' ,'s', 'h']

new = qiskit.compiler.transpile(qc, optimization_level=3, basis_gates=bgates)
new.draw()

In [ ]:
cirq.rz(np.pi/2)._unitary_() @ cirq.rz(np.pi/2)._unitary_()

In [ ]:
qc = QuantumCircuit(2)
qc.cnot(0,1)
qc.h(0)
qc.s(0)
qc.h(0)
qc.cnot(0,1)
print(qc.draw())

bgates = ['cx', 'u1', 'u2', 'u3']
# bgates = ['id', 'rz', 'sx', 'x', 'cx' ,'s', 'h', 'sxdg','sd']

new = qiskit.compiler.transpile(qc, optimization_level=3, basis_gates=bgates)
new.draw()

In [ ]:
backend = Aer.get_backend('unitary_simulator')
job = execute(new, backend)
op1 = job.result().get_unitary(new, decimals=3)

std = execute(qc, backend)
std1 = job.result().get_unitary(qc, decimals=3)

op1 == std1

In [ ]:
qc = QuantumCircuit(1)
qc.u2(-np.pi/2,np.pi/2, 0)
print(qc.draw())

backend = Aer.get_backend('unitary_simulator')
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

In [ ]:
cirq.rx(np.pi/2)._unitary_()

In [ ]:
cirq.Y._unitary_() @ cirq.S._unitary_() @ cirq.H._unitary_()

In [ ]:
(cirq.X**0.5)._unitary_() @ cirq.S._unitary_() 

In [ ]:
# bgates = ['id', 'rz', 'sx', 'x', 'cx' ,'s', 'h']
#[ 's', 'x', 'y', 'z', 'h', 'sdg', 'measure']
bgates = ['id', 'rz', 'sx', 'cx' ,'s', 'h']
new = qiskit.compiler.transpile(qc, optimization_level=3, basis_gates=bgates)
new.draw()

In [ ]:
backend = Aer.get_backend('unitary_simulator')
job = execute(new, backend)
job.result().get_unitary(new, decimals=3)

In [ ]:
print(qc.draw())

In [ ]:
qc = QuantumCircuit(2)
qc.cnot(0,1)
qc.h(0)
qc.s(0)
qc.h(0)
qc.cnot(0,1)

In [ ]:
qc = QuantumCircuit(1)
qc.sdg(0)
qc.h(0)
qc.s(0)
print(qc.draw())

# bgates = ['cx', 'u1', 'u2', 'u3']
bgates = ['id', 'rz', 'sx', 'x', 'cx' ,'s', 'h', 'sxdg','sdg' ,'y']

new = qiskit.compiler.transpile(qc, optimization_level=1, basis_gates=bgates)
new.draw()

In [ ]:
backend = Aer.get_backend('unitary_simulator')
job = execute(new, backend)
job.result().get_unitary(qc, decimals=3)

In [ ]:
qc = QuantumCircuit(2)
qc.h(0)
qc.cnot(0,1)
qc.s(0)
qc.h(0)
qc.s(0)
qc.rx(np.pi/2,1)
qc.rz(-np.pi/2,0)
print(qc.draw())

bgates = ['id', 'rz', 'sx', 'x', 'cx' ,'s', 'h', 'sxdg','sdg' ,'y']

new = qiskit.compiler.transpile(qc, optimization_level=1, basis_gates=bgates)
new.draw()

In [ ]:
qc = QuantumCircuit(2)
qc.cnot(0,1)
qc.h(1)
qc.cnot(0,1)
print(qc.draw())

bgates = ['id', 'rz', 'sx', 'x', 'cx' ,'s', 'h', 'sxdg','y']
# bgates = ['id', 'rz', 'x', 'cx' ,'s', 'h', 'sxdg','sdg' ,'y']
new = qiskit.compiler.transpile(qc, optimization_level=3, basis_gates=bgates)
new.draw()

In [373]:
qc = QuantumCircuit(1)
qc.sx(0)
qc.sx(0)
print(qc.draw())

backend = Aer.get_backend('unitary_simulator')
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

     ┌────┐┌────┐
q_0: ┤ √X ├┤ √X ├
     └────┘└────┘


array([[0.-0.j, 1.+0.j],
       [1.+0.j, 0.-0.j]])

In [ ]:
cirq.X._unitary_()

In [385]:
from qiskit import QuantumCircuit, Aer, execute
from qiskit.compiler import transpile
from cirq.contrib.qasm_import import circuit_from_qasm
def optimized_cirq_circuit_IBM_compiler(cirq_circuit, opt_level=3,
                               allowed_gates=['id', 'rz', 'ry', 'rx', 'cx' ,'s', 'h', 'sxdg','y','z'],
                                check_optimization = True):
    # id = identity
    
    # other possiblities:
        # ['cx', 'u1', 'u2', 'u3']
    
    cirq_qasm_file = cirq_circuit.to_qasm(header=False)
    
    ibm_circuit = QuantumCircuit.from_qasm_str(cirq_qasm_file)
#     print(ibm_circuit.draw())
    print(ibm_circuit.global_phase)
    
    simplified_circuit = transpile(ibm_circuit,#.reverse_bits(),
                                   optimization_level=opt_level,
                                   basis_gates=allowed_gates,
                                  approximation_degree=1)#no approximation
    
    
    global_phase = simplified_circuit.global_phase
    print(simplified_circuit.draw())
    print(global_phase)
    
    ibm_qasm = simplified_circuit.qasm()
    simplied_cirq_circuit = circuit_from_qasm(ibm_qasm)
    
    
#     if not np.isclose(global_phase, 0):
#         print(f'correcting global phase: {global_phase}')
#         qubit = list(simplied_cirq_circuit.all_qubits())[0]
    
#         if (np.isclose(global_phase, np.pi) or np.isclose(global_phase, -1*np.pi)):
#             op1 = cirq.rz(2*np.pi).on(qubit)
#             simplied_cirq_circuit.append(op1)
#         elif np.isclose(global_phase, +np.pi/2):
#             op1 = cirq.Z.on(qubit)
#             op2 = cirq.rz(-np.pi).on(qubit)
#             simplied_cirq_circuit.append([op1, op2])
#         elif np.isclose(global_phase, -np.pi/2):
#             op1 = cirq.Z.on(qubit)
#             op2 = cirq.rz(+np.pi).on(qubit) 
#             simplied_cirq_circuit.append([op1, op2])
#         elif np.isclose(global_phase, np.pi/4):
#             op1 = (cirq.S).on(qubit)
#             op2 = cirq.rz(-np.pi/2).on(qubit)
#             simplied_cirq_circuit.append([op1, op2])
#         elif np.isclose(global_phase, -np.pi/4):
#             op1 = (cirq.S**-1).on(qubit)
#             op2 = cirq.rz(np.pi/2).on(qubit)
#             simplied_cirq_circuit.append([op1, op2])
#         else:
#             print('cannot correct global phase using native gates')
#             print('adding cirq matrix gate')

#         phase_mat = np.eye(2)* np.e**(1j*phase)
#         phase_circuit = cirq.Circuit(cirq.MatrixGate(phase_mat).on(qubit))
#         simplied_cirq_circuit.append(list(phase_circuit.all_operations()))
    
    if check_optimization:
#         if not np.allclose(cirq_circuit.unitary(), simplied_cirq_circuit.unitary()):
#             raise ValueError('circuit compile incorrect')
        if not np.allclose(cirq_circuit.unitary(), np.e**(1j*2*global_phase)*simplied_cirq_circuit.unitary()):
            raise ValueError('circuit compile incorrect')
    return simplied_cirq_circuit, global_phase

In [712]:
from qiskit import QuantumCircuit, Aer, execute
from qiskit.compiler import transpile
from cirq.contrib.qasm_import import circuit_from_qasm
def optimized_cirq_circuit_IBM_compiler(cirq_circuit, opt_level=3,
                               allowed_gates=['id', 'rz', 'ry', 'rx', 'cx' ,'s', 'h', 'y','z'],
                                check_optimization = True):
    
    """
    Function that uses IBM's compiler to optimize cirq circuit.
    
    Note this function handles global phase for 0.25 intervals of pi
    Any other and a modified Zpow gate is used - this may lead to ISSUES, hence a has_modified_Zpow flag is
    returned!
    
    Args:
        cirq_circuit (cirq.Circuit): circuit to optimize
        opt_level (int): level of optimization (see qiskit.compiler.transpile for further details).
                             0: no optimization
                             1: light optimization
                             2: heavy optimization
                             3: even heavier optimization
        allowed_gates (list): list of strings of allowed qiskit gates
                                id: identity
                                cx: control x
                                sxdg: square root x dagger
                                sx: square root x
        
        check_optimization (bool): checks if unitaries of optimized circuit and unoptimized are the same
        
    """
    # id = identity
    
    # other possiblities:
        # ['cx', 'u1', 'u2', 'u3']
    
    cirq_qasm_file = cirq_circuit.to_qasm(header=False)
    
    ibm_circuit = QuantumCircuit.from_qasm_str(cirq_qasm_file)
    
    simplified_circuit = transpile(ibm_circuit,#.reverse_bits(),
                                   optimization_level=opt_level,
                                   basis_gates=allowed_gates,
                                  approximation_degree=1)#no approximation
    
    
#     global_phase = simplified_circuit.global_phase
#     print(simplified_circuit.draw())
    
    ibm_qasm = simplified_circuit.qasm()
    simplied_cirq_circuit = circuit_from_qasm(ibm_qasm)
    
    ########
    ## see matrix_equal function
    # https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/quantum_info/operators/predicates.py
    mat1 = cirq_circuit.unitary()
    for elt in mat1.flat:
            if abs(elt) > 0:
                theta = np.angle(elt)
                mat1 = np.exp(-1j * theta) * mat1
                break
    mat2 = simplied_cirq_circuit.unitary()
    for elt in mat2.flat:
        if abs(elt) > 0:
            phi = np.angle(elt)
            mat2 = np.exp(-1j * phi) * mat2
            break
    #######
    
    if check_optimization:
        print(f'phase circuit 1: {theta:.4f}')
        print(f'phase circuit 2:  {phi:.4f}')
        if not np.allclose(mat1, mat2):
            raise ValueError('circuit compile incorrect')
    
    ### correct global phase
    has_modified_Zpow = False
    if not np.isclose(ibm_circuit.global_phase, 0):
        raise ValueError('global phase issue')
    else:
        global_phase = phi
        if not np.isclose(global_phase, 0):
            qubit = list(simplied_cirq_circuit.all_qubits())[0]

            if (np.isclose(global_phase, np.pi) or np.isclose(global_phase, -1*np.pi)):
                op1 = cirq.rz(2*np.pi).on(qubit)
                simplied_cirq_circuit.append(op1)
            elif np.isclose(global_phase, -np.pi/2):
                op1 = cirq.Z.on(qubit)
                op2 = cirq.rz(-np.pi).on(qubit)
                simplied_cirq_circuit.append([op1, op2])
            elif np.isclose(global_phase, +np.pi/2):
                op1 = cirq.Z.on(qubit)
                op2 = cirq.rz(+np.pi).on(qubit) 
                simplied_cirq_circuit.append([op1, op2])
            elif np.isclose(global_phase, np.pi/4):
                op1 = (cirq.S**-1).on(qubit)
                op2 = cirq.rz(+np.pi/2).on(qubit)
                simplied_cirq_circuit.append([op1, op2])
            elif np.isclose(global_phase, -np.pi/4):
                op1 = (cirq.S).on(qubit)
                op2 = cirq.rz(-np.pi/2).on(qubit)
                simplied_cirq_circuit.append([op1, op2])
            else:
                phase_mat = np.eye(2)* np.e**(-1j*global_phase)
                Zpow_phase_correction_mat = cirq.ZPowGate(exponent=2, global_shift=-global_phase/(2*np.pi))._unitary_()
                if not (np.allclose(Zpow_phase_correction_mat, phase_mat)):
                    raise ValueError('circuit compile incorrect')
                
                op1 = cirq.ZPowGate(exponent=2, global_shift=-global_phase/(2*np.pi)).on(qubit)
                simplied_cirq_circuit.append(op1)
                has_modified_Zpow = True
                # could use cirq matrix gate instead:
#                 print('cannot correct global phase using native gates')
#                 print('adding cirq matrix gate')
#                 phase_circuit = cirq.Circuit(cirq.MatrixGate(phase_mat).on(qubit))
#                 simplied_cirq_circuit.append(list(phase_circuit.all_operations()))
    
    if check_optimization:
        if not np.allclose(cirq_circuit.unitary(), simplied_cirq_circuit.unitary()):
            raise ValueError('circuit compile incorrect')
    
    print('does circuit have modified Zpow:', 'yes'if has_modified_Zpow else 'no')
    return simplied_cirq_circuit, global_phase, has_modified_Zpow

In [698]:
test7 = cirq.Circuit(
cirq.CNOT(qbits[0], qbits[1]),
cirq.H(qbits[1]),
cirq.CNOT(qbits[0], qbits[1]),
cirq.S(qbits[1]),
cirq.S(qbits[0]),
)
print(test7)
np.around(test7.unitary(), 3)

0: ───@───────@───S───
      │       │
1: ───X───H───X───S───


array([[ 0.707+0.j   ,  0.707+0.j   ,  0.   +0.j   ,  0.   +0.j   ],
       [ 0.   +0.707j, -0.   -0.707j, -0.   +0.j   , -0.   +0.j   ],
       [-0.   +0.j   , -0.   +0.j   , -0.   -0.707j,  0.   +0.707j],
       [ 0.   +0.j   ,  0.   +0.j   , -0.707+0.j   , -0.707+0.j   ]])

In [713]:
out, phase, has_modified_Zpow = optimized_cirq_circuit_IBM_compiler(test7, check_optimization=True)
out

phase circuit 1: 0.0000
phase circuit 2:  -2.3562
does circuit have modified Zpow: yes


q_0: ───Rz(0.75π)────Ry(π)───Rz(-1.5π)───@───Ry(π)──────Rz(0.75π)───
                                         │
q_1: ───Rz(-0.75π)───Ry(π)───Rz(0.75π)───X───Rx(1.5π)───Z^0─────────

In [645]:
global_phase_circuit = cirq.Circuit(
cirq.ZPowGate(exponent=2, global_shift=-phase/(2*np.pi)).on(qbits[1]),
)
print(global_phase_circuit)
global_phase_circuit.unitary()

1: ───Z^0───


array([[-0.70710678+0.70710678j, -0.        +0.j        ],
       [-0.        +0.j        , -0.70710678+0.70710678j]])

In [658]:
global_phase_circuit = cirq.ConvertToCzAndSingleGates().optimize_circuit(circuit=global_phase_circuit) 
global_phase_circuit

In [646]:
# cirq.deconstruct_single_qubit_matrix_into_angles(global_phase_circuit.unitary())

(0.0, 0.0, -0.0)

In [596]:
phase

-2.356194490192345

In [561]:
from qiskit.extensions import UnitaryGate

xx = UnitaryGate(np.eye(2)*np.exp(-1j*phase))
# print(xx.to_matrix())

qc = QuantumCircuit(1)
qc.unitary(xx, [0], label='phase')
print(qc.draw())

bgates = ['id', 'rz', 'sx', 'x', 'cx' ,'s', 'h', 'sxdg','y']
# bgates = ['id', 'rz', 'x', 'cx' ,'s', 'h', 'sxdg','sdg' ,'y']
new = transpile(qc, optimization_level=3, basis_gates=bgates)
new.draw()

     ┌───────┐
q_0: ┤ phase ├
     └───────┘


global phase: -5π/4
     
q_0:

In [521]:
np.around(out.unitary(), 3) 

array([[ 0.707+0.j,  0.707+0.j,  0.   +0.j,  0.   +0.j],
       [ 0.707+0.j, -0.707-0.j,  0.   +0.j,  0.   +0.j],
       [ 0.   +0.j,  0.   +0.j, -0.707+0.j,  0.707+0.j],
       [ 0.   +0.j,  0.   +0.j,  0.707-0.j,  0.707+0.j]])

In [524]:
 np.around(test7.unitary(), 3) 

array([[ 0.707+0.j,  0.707+0.j,  0.   +0.j,  0.   +0.j],
       [ 0.707+0.j, -0.707+0.j, -0.   +0.j, -0.   +0.j],
       [-0.   +0.j, -0.   +0.j, -0.707+0.j,  0.707+0.j],
       [ 0.   +0.j,  0.   +0.j,  0.707+0.j,  0.707+0.j]])

In [500]:
np.e**(1j*phase)

(0.7071067811865476-0.7071067811865475j)

In [78]:
np.e**(-1j*np.pi/2)

(6.123233995736766e-17-1j)

In [232]:
np.around(np.eye(2)* np.e**(1j*np.pi/4), 3) 

array([[0.707+0.707j, 0.   +0.j   ],
       [0.   +0.j   , 0.707+0.707j]])

In [233]:
np.around(
cirq.Circuit(
cirq.S(qbits[0]),
cirq.rz(-np.pi/2).on(qbits[0]),
).unitary()
,3)

array([[0.707+0.707j, 0.   +0.j   ],
       [0.   +0.j   , 0.707+0.707j]])

In [83]:
np.around(
cirq.Circuit(
cirq.S(qbits[1])**-1,
cirq.rz(np.pi/2).on(qbits[1]),
cirq.I(qbits[0])    
).unitary()
,3)

array([[0.707-0.707j, 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.707-0.707j, 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.707-0.707j, 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.707-0.707j]])

In [ ]:
np.around(np.eye(4)* np.e**(-1j*phase), 3)

In [ ]:
circuit = cirq.Circuit(
(cirq.S**-1).on(qbits[0]),
cirq.rz(-2*phase).on(qbits[0]),
# (cirq.S**-1).on(qbits[0]),
cirq.I.on(qbits[1])
)

print(circuit)
np.around(circuit.unitary(), 3)

In [ ]:
(cirq.S**-1).on(qbits[0]),

In [ ]:
np.around(out.unitary()* np.e**(1j*phase), 3) 

In [ ]:
np.around(test7.unitary(), 3) == np.around(out.unitary(),3)

In [ ]:
new = new.reverse_bits()
new.draw()

In [ ]:
np.around(np.eye(2)* np.e**(-1j*2.4), 3)

In [ ]:
1j*np.e**(1j*np.pi/4) == np.e**(-1j*np.pi/4)

In [ ]:
phase

In [ ]:
cirq.Circuit(cirq.ops.GlobalPhaseOperation(
    coefficient= np.e**(-1j*phase),
#     atol: float = 1e-08
).on(qbits[0]))


In [ ]:
mat_with_corr_phase

In [ ]:
from quchem.Qcircuit.Circuit_functions_to_create_arb_state import Single_qubit_rotation

Single_qubit_rotation((0.87758256-0.47942554j), 0)

In [ ]:
(cirq.S)._unitary_() @ (cirq.rz(-np.pi/2))._unitary_()

In [ ]:
(cirq.S**-1)._unitary_() @ (cirq.rz(np.pi/2))._unitary_()

In [ ]:
(cirq.S)._unitary_() @ (cirq.rz(-np.pi))._unitary_()

In [ ]:
np.e**(-1j*np.pi/2)

In [ ]:
np.e**(1j*np.pi/2)