In [1]:
from quchem.Hamiltonian_Generator_Functions import *

In [2]:
### Variable Parameters
# Molecule = 'H2'
# geometry = [('H', (0., 0., 0.)), ('H', (0., 0., 0.74))]

Molecule = 'LiH'
geometry = [('Li', (0., 0., 0.)), ('H', (0., 0., 1.45))]

In [3]:
### initialise Hamiltonian class
Hamilt = Hamiltonian(Molecule,
                     run_scf=1, run_mp2=1, run_cisd=1, run_ccsd=1, run_fci=1,
                     basis='sto-3g',
                     multiplicity=1,
                     geometry=geometry)  # normally None!

In [4]:
Hamilt.Get_Molecular_Hamiltonian(Get_H_matrix=True)

In [5]:
#give second quant molecular Hamiltonian:
print(Hamilt.MolecularHamiltonian)


#if Get_H_matrix=True ... then the matrix of this Hamiltonian is found
Hamilt.MolecularHamiltonianMatrix.todense()

() 1.094849401386207
((0, 1), (0, 0)) -4.761263394734209
((0, 1), (2, 0)) -0.1120251934488058
((0, 1), (4, 0)) -0.1687622851622621
((0, 1), (10, 0)) -0.020097736915665104
((1, 1), (1, 0)) -4.761263394734209
((1, 1), (3, 0)) -0.1120251934488058
((1, 1), (5, 0)) -0.1687622851622621
((1, 1), (11, 0)) -0.020097736915665104
((2, 1), (0, 0)) -0.11202519344880557
((2, 1), (2, 0)) -1.552428782940138
((2, 1), (4, 0)) 0.03692607075821791
((2, 1), (10, 0)) 0.10044688727812501
((3, 1), (1, 0)) -0.11202519344880557
((3, 1), (3, 0)) -1.552428782940138
((3, 1), (5, 0)) 0.03692607075821791
((3, 1), (11, 0)) 0.10044688727812501
((4, 1), (0, 0)) -0.16876228516226222
((4, 1), (2, 0)) 0.036926070758217924
((4, 1), (4, 0)) -1.1362024585491723
((4, 1), (10, 0)) -0.033189648568136304
((5, 1), (1, 0)) -0.16876228516226222
((5, 1), (3, 0)) 0.036926070758217924
((5, 1), (5, 0)) -1.1362024585491723
((5, 1), (11, 0)) -0.033189648568136304
((6, 1), (6, 0)) -1.1502630292982357
((7, 1), (7, 0)) -1.1502630292982357
(

matrix([[ 1.0948494 +0.j,  0.        +0.j,  0.        +0.j, ...,
          0.        +0.j,  0.        +0.j,  0.        +0.j],
        [ 0.        +0.j,  0.16965897+0.j,  0.        +0.j, ...,
          0.        +0.j,  0.        +0.j,  0.        +0.j],
        [ 0.        +0.j,  0.        +0.j,  0.16965897+0.j, ...,
          0.        +0.j,  0.        +0.j,  0.        +0.j],
        ...,
        [ 0.        +0.j,  0.        +0.j,  0.        +0.j, ...,
         -0.82363019+0.j,  0.        +0.j,  0.        +0.j],
        [ 0.        +0.j,  0.        +0.j,  0.        +0.j, ...,
          0.        +0.j, -0.82363019+0.j,  0.        +0.j],
        [ 0.        +0.j,  0.        +0.j,  0.        +0.j, ...,
          0.        +0.j,  0.        +0.j,  1.71819535+0.j]])

In [6]:
# as we can perform a CCSD in PSI4 we can get the coupled cluster amplitudes:

Hamilt.Get_CCSD_Amplitudes()

# single e- amplitudes:
print(Hamilt.molecule.single_cc_amplitudes)

# double e- amplitudes:
print(Hamilt.molecule.double_cc_amplitudes)

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [-0.00031898  0.          0.03503389  0.          0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.         -0.00031898  0.          0.03503389  0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.        

In [12]:
Hamilt.Get_Qubit_Hamiltonian(threshold=None, transformation='JW')

(-4.087119674570706+0j) [] +
(-0.0038842764949217476+0j) [X0 X1 Y2 Y3] +
(-0.0029339033345401134+0j) [X0 X1 Y2 Z3 Z4 Y5] +
(-0.0018887651657346948+0j) [X0 X1 Y2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Y11] +
(-0.0029339033345401134+0j) [X0 X1 X3 X4] +
(-0.0018887651657346948+0j) [X0 X1 X3 Z4 Z5 Z6 Z7 Z8 Z9 X10] +
(-0.005355522464331686+0j) [X0 X1 Y4 Y5] +
(-0.00015005041403618274+0j) [X0 X1 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Y11] +
(-0.00015005041403618274+0j) [X0 X1 X5 Z6 Z7 Z8 Z9 X10] +
(-0.0024550578367610178+0j) [X0 X1 Y6 Y7] +
(-0.0024550578367610217+0j) [X0 X1 Y8 Y9] +
(-0.0016211187515762838+0j) [X0 X1 Y10 Y11] +
(0.0038842764949217476+0j) [X0 Y1 Y2 X3] +
(0.0029339033345401134+0j) [X0 Y1 Y2 Z3 Z4 X5] +
(0.0018887651657346948+0j) [X0 Y1 Y2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 X11] +
(-0.0029339033345401134+0j) [X0 Y1 Y3 X4] +
(-0.0018887651657346948+0j) [X0 Y1 Y3 Z4 Z5 Z6 Z7 Z8 Z9 X10] +
(0.005355522464331686+0j) [X0 Y1 Y4 X5] +
(0.00015005041403618274+0j) [X0 Y1 Y4 Z5 Z6 Z7 Z8 Z9 Z10 X11] +
(-0.00015005041403618274+0

In [13]:
Hamilt.Get_Qubit_Hamiltonian(threshold=None, transformation='BK')

(-4.087119674570706+0j) [] +
(-0.029967968692009555+0j) [X0 X1 X2] +
(-0.001590575077303519+0j) [X0 X1 X2 X3 Y7 Y11] +
(-0.0009609799433304498+0j) [X0 X1 X2 Y3 Y5] +
(-0.0019616720126671835+0j) [X0 X1 X2 Z3] +
(0.0029466270172430354+0j) [X0 X1 Z2 X3 Y7 Z9 Y10 X11] +
(-0.003479120544228968+0j) [X0 X1 Z2 Y3 Y4 X5] +
(-0.0011402387562956847+0j) [X0 X1 X3 X4 Y7 Y11] +
(-0.001229455015296837+0j) [X0 X1 X3 Y4 Y5 Z6 Z7] +
(0.0011402387562956847+0j) [X0 X1 X3 Y4 Z5 Y7 Z9 Z10 X11] +
(-0.0025595117802951215+0j) [X0 X1 X3 Z4 Y5 Y6 Z7] +
(-0.002264086917424176+0j) [X0 X1 X3 Z4 Z5 Y7 Z9 Y10 X11] +
(-0.001123848161128491+0j) [X0 X1 X3 Z4 Y7 Z9 Y10 X11] +
(0.0014751106104476744+0j) [X0 X1 X3 X6 Y7 Y11] +
(-0.0014624417163224357+0j) [X0 X1 X3 Z6 Y7 Z9 Y10 X11] +
(0.001475110610447677+0j) [X0 X1 X3 Y7 X8 Y11] +
(-0.001475110610447677+0j) [X0 X1 X3 Y7 Y8 Z10 X11] +
(-0.0014624417163224366+0j) [X0 X1 X3 Y7 Z8 Z9 Y10 X11] +
(1.2668894125240632e-05+0j) [X0 X1 X3 Y7 Z8 Y10 X11] +
(0.0008829229484264042+0j) 

# NOON

In [ ]:
NOON, NMO_basis = Hamilt.Get_NOON()
print(NOON)

In [14]:
one_RDM = Hamilt.molecule.fci_one_rdm
one_rdm_a = one_RDM[np.arange(0,Hamilt.molecule.n_qubits,2)][:,np.arange(0,Hamilt.molecule.n_qubits,2)]
one_rdm_b = one_RDM[np.arange(1,Hamilt.molecule.n_qubits,2)][:,np.arange(1,Hamilt.molecule.n_qubits,2)]

combined = one_rdm_a + one_rdm_b
combined

array([[ 1.99991115e+00,  4.71916570e-04, -4.70503103e-04,
        -1.83799712e-16, -1.67373982e-16, -1.20133254e-03],
       [ 4.71916570e-04,  1.95968686e+00,  6.69066973e-02,
         2.17037148e-16,  3.77557562e-16, -8.41805821e-03],
       [-4.70503103e-04,  6.69066973e-02,  9.67894009e-03,
         1.81135849e-17,  3.58512093e-17,  1.38466239e-02],
       [-1.83799712e-16,  2.17037148e-16,  1.81135849e-17,
         1.72048547e-03, -3.39069618e-17,  1.59558233e-17],
       [-1.67373982e-16,  3.77557562e-16,  3.58512093e-17,
        -3.39069618e-17,  1.72048547e-03,  4.30472698e-17],
       [-1.20133254e-03, -8.41805821e-03,  1.38466239e-02,
         1.59558233e-17,  4.30472698e-17,  2.72820764e-02]])

In [16]:
from numpy.linalg import eig
eig_values, eig_vectors = eig(combined)
eig_values

array([1.99991759e+00, 1.96200679e+00, 3.45854731e-02, 4.91748520e-05,
       1.72048547e-03, 1.72048547e-03])

In [17]:
basis_transformation_matrix = eig_vectors.transpose()
basis_transformation_matrix

array([[-9.99926007e-01, -1.21456852e-02, -1.67329693e-04,
         9.06562343e-17,  8.14725921e-17,  6.59609832e-04],
       [-1.21468993e-02,  9.99332071e-01,  3.42212054e-02,
         1.12429549e-16,  1.94047685e-16, -4.09567050e-03],
       [-6.55681259e-04,  1.21332683e-02, -4.60760946e-01,
        -6.08993885e-16, -1.52228879e-15, -8.87441099e-01],
       [ 6.06046451e-05,  3.22595522e-02, -8.86864269e-01,
         1.07441690e-15, -1.28720562e-16,  4.60902469e-01],
       [ 9.54943745e-17, -1.88589185e-16, -7.27596347e-16,
         1.48307288e-01,  9.88941327e-01, -1.42556663e-15],
       [-7.81943972e-17,  1.17718633e-16, -9.71793742e-16,
        -9.88855015e-01,  1.48881694e-01,  9.13831966e-16]])

In [22]:
# Diag_matix = C^{-1} A C

#this could be wrong:
Diag_matix = np.dot(np.linalg.inv(basis_transformation_matrix) , np.dot(np.diag(combined), basis_transformation_matrix))
Diag_matix

array([ 1.99988708,  1.95742126,  0.06224302,  0.01520124,  0.00354804,
       -0.07547905])